System.config({
  defaultJSExtensions: true,
  transpiler: "babel",
  babelOptions: {
    "optional": [
      "es7.decorators",
      "es7.classProperties"
    ]
  },
  paths: {
    "*": "dist/*",
    "github:*": "jspm_packages/github/*",
    "npm:*": "jspm_packages/npm/*"
  },
  meta: {
    "../assets/plugins/revoslider/js/jquery.themepunch.tools.min.js": {
      "deps": [
        "jquery"
      ]
    }
  },
  map: {
    "aurelia-animator-css": "npm:aurelia-animator-css@1.0.0-beta.1.0.3",
    "aurelia-bootstrapper": "npm:aurelia-bootstrapper@1.0.0-beta.1.0.2",
    "aurelia-fetch-client": "npm:aurelia-fetch-client@1.0.0-beta.1.0.2",
    "aurelia-framework": "npm:aurelia-framework@1.0.0-beta.1.1.3",
    "aurelia-history-browser": "npm:aurelia-history-browser@1.0.0-beta.1.0.1",
    "aurelia-loader-default": "npm:aurelia-loader-default@1.0.0-beta.1.0.2",
    "aurelia-logging-console": "npm:aurelia-logging-console@1.0.0-beta.1",
    "aurelia-router": "npm:aurelia-router@1.0.0-beta.1.0.1",
    "aurelia-templating-binding": "npm:aurelia-templating-binding@1.0.0-beta.1.0.2",
    "aurelia-templating-resources": "npm:aurelia-templating-resources@1.0.0-beta.1.0.4",
    "aurelia-templating-router": "npm:aurelia-templating-router@1.0.0-beta.1.0.5",
    "aurelia-validation": "github:aurelia/validation@0.6.2",
    "babel": "npm:babel-core@5.8.34",
    "babel-runtime": "npm:babel-runtime@5.8.34",
    "beatgammit/base64-js": "github:beatgammit/base64-js@1.1.1",
    "bootstrap": "github:twbs/bootstrap@3.3.6",
    "bootstrap-slider": "github:seiyria/bootstrap-slider@6.0.17",
    "braintree/braintree-web": "github:braintree/braintree-web@2.21.0",
    "core-js": "npm:core-js@1.2.6",
    "dankogai/js-base64": "github:dankogai/js-base64@2.1.9",
    "fetch": "github:github/fetch@0.10.1",
    "font-awesome": "npm:font-awesome@4.5.0",
    "google-recaptcha": "github:itmcdev/aurelia-google-recaptcha@master",
    "jquery": "github:components/jquery@2.2.0",
    "jspdf": "npm:jspdf@1.2.61",
    "jspm/nodelibs-crypto": "github:jspm/nodelibs-crypto@0.1.0",
    "parsleyjs": "github:guillaumepotier/Parsley.js@2.3.4",
    "text": "github:systemjs/plugin-text@0.0.3",
    "tsironis/lockr": "github:tsironis/lockr@0.8.4",
    "github:aurelia/validation@0.6.2": {
      "aurelia-binding": "npm:aurelia-binding@1.0.0-beta.1.1.3",
      "aurelia-dependency-injection": "npm:aurelia-dependency-injection@1.0.0-beta.1.1.3",
      "aurelia-logging": "npm:aurelia-logging@1.0.0-beta.1.1.1",
      "aurelia-metadata": "npm:aurelia-metadata@1.0.0-beta.1.1.4",
      "aurelia-templating": "npm:aurelia-templating@1.0.0-beta.1.1.1"
    },
    "github:guillaumepotier/Parsley.js@2.3.4": {
      "jquery": "github:components/jquery@2.2.0"
    },
    "github:itmcdev/aurelia-google-recaptcha@master": {
      "aurelia-framework": "npm:aurelia-framework@1.0.0-beta.1.1.3"
    },
    "github:jspm/nodelibs-assert@0.1.0": {
      "assert": "npm:assert@1.3.0"
    },
    "github:jspm/nodelibs-buffer@0.1.0": {
      "buffer": "npm:buffer@3.6.0"
    },
    "github:jspm/nodelibs-constants@0.1.0": {
      "constants-browserify": "npm:constants-browserify@0.0.1"
    },
    "github:jspm/nodelibs-crypto@0.1.0": {
      "crypto-browserify": "npm:crypto-browserify@3.11.0"
    },
    "github:jspm/nodelibs-events@0.1.1": {
      "events": "npm:events@1.0.2"
    },
    "github:jspm/nodelibs-path@0.1.0": {
      "path-browserify": "npm:path-browserify@0.0.0"
    },
    "github:jspm/nodelibs-process@0.1.2": {
      "process": "npm:process@0.11.2"
    },
    "github:jspm/nodelibs-stream@0.1.0": {
      "stream-browserify": "npm:stream-browserify@1.0.0"
    },
    "github:jspm/nodelibs-string_decoder@0.1.0": {
      "string_decoder": "npm:string_decoder@0.10.31"
    },
    "github:jspm/nodelibs-util@0.1.0": {
      "util": "npm:util@0.10.3"
    },
    "github:jspm/nodelibs-vm@0.1.0": {
      "vm-browserify": "npm:vm-browserify@0.0.4"
    },
    "github:twbs/bootstrap@3.3.6": {
      "jquery": "github:components/jquery@2.2.0"
    },
    "npm:asn1.js@4.5.1": {
      "assert": "github:jspm/nodelibs-assert@0.1.0",
      "bn.js": "npm:bn.js@4.10.5",
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "fs": "github:jspm/nodelibs-fs@0.1.2",
      "inherits": "npm:inherits@2.0.1",
      "minimalistic-assert": "npm:minimalistic-assert@1.0.0",
      "vm": "github:jspm/nodelibs-vm@0.1.0"
    },
    "npm:assert@1.3.0": {
      "util": "npm:util@0.10.3"
    },
    "npm:aurelia-animator-css@1.0.0-beta.1.0.3": {
      "aurelia-metadata": "npm:aurelia-metadata@1.0.0-beta.1.1.4",
      "aurelia-pal": "npm:aurelia-pal@1.0.0-beta.1.1.1",
      "aurelia-templating": "npm:aurelia-templating@1.0.0-beta.1.1.1"
    },
    "npm:aurelia-binding@1.0.0-beta.1.1.3": {
      "aurelia-metadata": "npm:aurelia-metadata@1.0.0-beta.1.1.4",
      "aurelia-pal": "npm:aurelia-pal@1.0.0-beta.1.1.1",
      "aurelia-task-queue": "npm:aurelia-task-queue@1.0.0-beta.1.1.1",
      "core-js": "npm:core-js@2.1.1"
    },
    "npm:aurelia-bootstrapper@1.0.0-beta.1.0.2": {
      "aurelia-event-aggregator": "npm:aurelia-event-aggregator@1.0.0-beta.1",
      "aurelia-framework": "npm:aurelia-framework@1.0.0-beta.1.1.3",
      "aurelia-history": "npm:aurelia-history@1.0.0-beta.1",
      "aurelia-history-browser": "npm:aurelia-history-browser@1.0.0-beta.1.0.1",
      "aurelia-loader-default": "npm:aurelia-loader-default@1.0.0-beta.1.0.2",
      "aurelia-logging-console": "npm:aurelia-logging-console@1.0.0-beta.1",
      "aurelia-pal": "npm:aurelia-pal@1.0.0-beta.1.1.1",
      "aurelia-pal-browser": "npm:aurelia-pal-browser@1.0.0-beta.1.0.3",
      "aurelia-router": "npm:aurelia-router@1.0.0-beta.1.0.1",
      "aurelia-templating": "npm:aurelia-templating@1.0.0-beta.1.1.1",
      "aurelia-templating-binding": "npm:aurelia-templating-binding@1.0.0-beta.1.0.2",
      "aurelia-templating-resources": "npm:aurelia-templating-resources@1.0.0-beta.1.0.4",
      "aurelia-templating-router": "npm:aurelia-templating-router@1.0.0-beta.1.0.5",
      "core-js": "npm:core-js@1.2.6"
    },
    "npm:aurelia-dependency-injection@1.0.0-beta.1.1.3": {
      "aurelia-logging": "npm:aurelia-logging@1.0.0-beta.1.1.1",
      "aurelia-metadata": "npm:aurelia-metadata@1.0.0-beta.1.1.4",
      "aurelia-pal": "npm:aurelia-pal@1.0.0-beta.1.1.1",
      "core-js": "npm:core-js@2.1.1"
    },
    "npm:aurelia-event-aggregator@1.0.0-beta.1": {
      "aurelia-logging": "npm:aurelia-logging@1.0.0-beta.1.1.1"
    },
    "npm:aurelia-fetch-client@1.0.0-beta.1.0.2": {
      "core-js": "npm:core-js@1.2.6"
    },
    "npm:aurelia-framework@1.0.0-beta.1.1.3": {
      "aurelia-binding": "npm:aurelia-binding@1.0.0-beta.1.1.3",
      "aurelia-dependency-injection": "npm:aurelia-dependency-injection@1.0.0-beta.1.1.3",
      "aurelia-loader": "npm:aurelia-loader@1.0.0-beta.1.1.1",
      "aurelia-logging": "npm:aurelia-logging@1.0.0-beta.1.1.1",
      "aurelia-metadata": "npm:aurelia-metadata@1.0.0-beta.1.1.4",
      "aurelia-pal": "npm:aurelia-pal@1.0.0-beta.1.1.1",
      "aurelia-path": "npm:aurelia-path@1.0.0-beta.1.1.0",
      "aurelia-task-queue": "npm:aurelia-task-queue@1.0.0-beta.1.1.1",
      "aurelia-templating": "npm:aurelia-templating@1.0.0-beta.1.1.1",
      "core-js": "npm:core-js@2.1.1"
    },
    "npm:aurelia-history-browser@1.0.0-beta.1.0.1": {
      "aurelia-history": "npm:aurelia-history@1.0.0-beta.1",
      "aurelia-pal": "npm:aurelia-pal@1.0.0-beta.1.1.1",
      "core-js": "npm:core-js@1.2.6"
    },
    "npm:aurelia-loader-default@1.0.0-beta.1.0.2": {
      "aurelia-loader": "npm:aurelia-loader@1.0.0-beta.1.1.1",
      "aurelia-metadata": "npm:aurelia-metadata@1.0.0-beta.1.1.4",
      "aurelia-pal": "npm:aurelia-pal@1.0.0-beta.1.1.1"
    },
    "npm:aurelia-loader@1.0.0-beta.1.1.1": {
      "aurelia-metadata": "npm:aurelia-metadata@1.0.0-beta.1.1.4",
      "aurelia-path": "npm:aurelia-path@1.0.0-beta.1.1.0"
    },
    "npm:aurelia-logging-console@1.0.0-beta.1": {
      "aurelia-logging": "npm:aurelia-logging@1.0.0-beta.1.1.1",
      "aurelia-pal": "npm:aurelia-pal@1.0.0-beta.1.1.1"
    },
    "npm:aurelia-metadata@1.0.0-beta.1.1.4": {
      "aurelia-pal": "npm:aurelia-pal@1.0.0-beta.1.1.1",
      "core-js": "npm:core-js@2.1.1"
    },
    "npm:aurelia-pal-browser@1.0.0-beta.1.0.3": {
      "aurelia-pal": "npm:aurelia-pal@1.0.0-beta.1.1.1",
      "core-js": "npm:core-js@1.2.6"
    },
    "npm:aurelia-route-recognizer@1.0.0-beta.1": {
      "aurelia-path": "npm:aurelia-path@1.0.0-beta.1.1.0",
      "core-js": "npm:core-js@1.2.6"
    },
    "npm:aurelia-router@1.0.0-beta.1.0.1": {
      "aurelia-dependency-injection": "npm:aurelia-dependency-injection@1.0.0-beta.1.1.3",
      "aurelia-event-aggregator": "npm:aurelia-event-aggregator@1.0.0-beta.1",
      "aurelia-history": "npm:aurelia-history@1.0.0-beta.1",
      "aurelia-logging": "npm:aurelia-logging@1.0.0-beta.1.1.1",
      "aurelia-path": "npm:aurelia-path@1.0.0-beta.1.1.0",
      "aurelia-route-recognizer": "npm:aurelia-route-recognizer@1.0.0-beta.1",
      "core-js": "npm:core-js@1.2.6"
    },
    "npm:aurelia-task-queue@1.0.0-beta.1.1.1": {
      "aurelia-pal": "npm:aurelia-pal@1.0.0-beta.1.1.1"
    },
    "npm:aurelia-templating-binding@1.0.0-beta.1.0.2": {
      "aurelia-binding": "npm:aurelia-binding@1.0.0-beta.1.1.3",
      "aurelia-logging": "npm:aurelia-logging@1.0.0-beta.1.1.1",
      "aurelia-templating": "npm:aurelia-templating@1.0.0-beta.1.1.1"
    },
    "npm:aurelia-templating-resources@1.0.0-beta.1.0.4": {
      "aurelia-binding": "npm:aurelia-binding@1.0.0-beta.1.1.3",
      "aurelia-dependency-injection": "npm:aurelia-dependency-injection@1.0.0-beta.1.1.3",
      "aurelia-loader": "npm:aurelia-loader@1.0.0-beta.1.1.1",
      "aurelia-logging": "npm:aurelia-logging@1.0.0-beta.1.1.1",
      "aurelia-pal": "npm:aurelia-pal@1.0.0-beta.1.1.1",
      "aurelia-path": "npm:aurelia-path@1.0.0-beta.1.1.0",
      "aurelia-task-queue": "npm:aurelia-task-queue@1.0.0-beta.1.1.1",
      "aurelia-templating": "npm:aurelia-templating@1.0.0-beta.1.1.1",
      "core-js": "npm:core-js@1.2.6"
    },
    "npm:aurelia-templating-router@1.0.0-beta.1.0.5": {
      "aurelia-dependency-injection": "npm:aurelia-dependency-injection@1.0.0-beta.1.1.3",
      "aurelia-logging": "npm:aurelia-logging@1.0.0-beta.1.1.1",
      "aurelia-metadata": "npm:aurelia-metadata@1.0.0-beta.1.1.4",
      "aurelia-pal": "npm:aurelia-pal@1.0.0-beta.1.1.1",
      "aurelia-path": "npm:aurelia-path@1.0.0-beta.1.1.0",
      "aurelia-router": "npm:aurelia-router@1.0.0-beta.1.0.1",
      "aurelia-templating": "npm:aurelia-templating@1.0.0-beta.1.1.1"
    },
    "npm:aurelia-templating@1.0.0-beta.1.1.1": {
      "aurelia-binding": "npm:aurelia-binding@1.0.0-beta.1.1.3",
      "aurelia-dependency-injection": "npm:aurelia-dependency-injection@1.0.0-beta.1.1.3",
      "aurelia-loader": "npm:aurelia-loader@1.0.0-beta.1.1.1",
      "aurelia-logging": "npm:aurelia-logging@1.0.0-beta.1.1.1",
      "aurelia-metadata": "npm:aurelia-metadata@1.0.0-beta.1.1.4",
      "aurelia-pal": "npm:aurelia-pal@1.0.0-beta.1.1.1",
      "aurelia-path": "npm:aurelia-path@1.0.0-beta.1.1.0",
      "aurelia-task-queue": "npm:aurelia-task-queue@1.0.0-beta.1.1.1",
      "core-js": "npm:core-js@2.1.1"
    },
    "npm:babel-runtime@5.8.34": {
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:bn.js@4.10.5": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0"
    },
    "npm:browserify-aes@1.0.6": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "buffer-xor": "npm:buffer-xor@1.0.3",
      "cipher-base": "npm:cipher-base@1.0.2",
      "create-hash": "npm:create-hash@1.1.2",
      "crypto": "github:jspm/nodelibs-crypto@0.1.0",
      "evp_bytestokey": "npm:evp_bytestokey@1.0.0",
      "fs": "github:jspm/nodelibs-fs@0.1.2",
      "inherits": "npm:inherits@2.0.1",
      "systemjs-json": "github:systemjs/plugin-json@0.1.0"
    },
    "npm:browserify-cipher@1.0.0": {
      "browserify-aes": "npm:browserify-aes@1.0.6",
      "browserify-des": "npm:browserify-des@1.0.0",
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "crypto": "github:jspm/nodelibs-crypto@0.1.0",
      "evp_bytestokey": "npm:evp_bytestokey@1.0.0"
    },
    "npm:browserify-des@1.0.0": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "cipher-base": "npm:cipher-base@1.0.2",
      "crypto": "github:jspm/nodelibs-crypto@0.1.0",
      "des.js": "npm:des.js@1.0.0",
      "inherits": "npm:inherits@2.0.1"
    },
    "npm:browserify-rsa@4.0.1": {
      "bn.js": "npm:bn.js@4.10.5",
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "constants": "github:jspm/nodelibs-constants@0.1.0",
      "crypto": "github:jspm/nodelibs-crypto@0.1.0",
      "randombytes": "npm:randombytes@2.0.2"
    },
    "npm:browserify-sign@4.0.0": {
      "bn.js": "npm:bn.js@4.10.5",
      "browserify-rsa": "npm:browserify-rsa@4.0.1",
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "create-hash": "npm:create-hash@1.1.2",
      "create-hmac": "npm:create-hmac@1.1.4",
      "crypto": "github:jspm/nodelibs-crypto@0.1.0",
      "elliptic": "npm:elliptic@6.2.3",
      "inherits": "npm:inherits@2.0.1",
      "parse-asn1": "npm:parse-asn1@5.0.0",
      "stream": "github:jspm/nodelibs-stream@0.1.0"
    },
    "npm:buffer-xor@1.0.3": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "systemjs-json": "github:systemjs/plugin-json@0.1.0"
    },
    "npm:buffer@3.6.0": {
      "base64-js": "npm:base64-js@0.0.8",
      "child_process": "github:jspm/nodelibs-child_process@0.1.0",
      "fs": "github:jspm/nodelibs-fs@0.1.2",
      "ieee754": "npm:ieee754@1.1.6",
      "isarray": "npm:isarray@1.0.0",
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:cipher-base@1.0.2": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "inherits": "npm:inherits@2.0.1",
      "stream": "github:jspm/nodelibs-stream@0.1.0",
      "string_decoder": "github:jspm/nodelibs-string_decoder@0.1.0"
    },
    "npm:constants-browserify@0.0.1": {
      "systemjs-json": "github:systemjs/plugin-json@0.1.0"
    },
    "npm:core-js@1.2.6": {
      "fs": "github:jspm/nodelibs-fs@0.1.2",
      "path": "github:jspm/nodelibs-path@0.1.0",
      "process": "github:jspm/nodelibs-process@0.1.2",
      "systemjs-json": "github:systemjs/plugin-json@0.1.0"
    },
    "npm:core-js@2.1.1": {
      "fs": "github:jspm/nodelibs-fs@0.1.2",
      "path": "github:jspm/nodelibs-path@0.1.0",
      "process": "github:jspm/nodelibs-process@0.1.2",
      "systemjs-json": "github:systemjs/plugin-json@0.1.0"
    },
    "npm:core-util-is@1.0.2": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0"
    },
    "npm:create-ecdh@4.0.0": {
      "bn.js": "npm:bn.js@4.10.5",
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "crypto": "github:jspm/nodelibs-crypto@0.1.0",
      "elliptic": "npm:elliptic@6.2.3"
    },
    "npm:create-hash@1.1.2": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "cipher-base": "npm:cipher-base@1.0.2",
      "crypto": "github:jspm/nodelibs-crypto@0.1.0",
      "fs": "github:jspm/nodelibs-fs@0.1.2",
      "inherits": "npm:inherits@2.0.1",
      "ripemd160": "npm:ripemd160@1.0.1",
      "sha.js": "npm:sha.js@2.4.5"
    },
    "npm:create-hmac@1.1.4": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "create-hash": "npm:create-hash@1.1.2",
      "crypto": "github:jspm/nodelibs-crypto@0.1.0",
      "inherits": "npm:inherits@2.0.1",
      "stream": "github:jspm/nodelibs-stream@0.1.0"
    },
    "npm:crypto-browserify@3.11.0": {
      "browserify-cipher": "npm:browserify-cipher@1.0.0",
      "browserify-sign": "npm:browserify-sign@4.0.0",
      "create-ecdh": "npm:create-ecdh@4.0.0",
      "create-hash": "npm:create-hash@1.1.2",
      "create-hmac": "npm:create-hmac@1.1.4",
      "diffie-hellman": "npm:diffie-hellman@5.0.2",
      "inherits": "npm:inherits@2.0.1",
      "pbkdf2": "npm:pbkdf2@3.0.4",
      "public-encrypt": "npm:public-encrypt@4.0.0",
      "randombytes": "npm:randombytes@2.0.2"
    },
    "npm:des.js@1.0.0": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "inherits": "npm:inherits@2.0.1",
      "minimalistic-assert": "npm:minimalistic-assert@1.0.0"
    },
    "npm:diffie-hellman@5.0.2": {
      "bn.js": "npm:bn.js@4.10.5",
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "crypto": "github:jspm/nodelibs-crypto@0.1.0",
      "miller-rabin": "npm:miller-rabin@4.0.0",
      "randombytes": "npm:randombytes@2.0.2",
      "systemjs-json": "github:systemjs/plugin-json@0.1.0"
    },
    "npm:elliptic@6.2.3": {
      "bn.js": "npm:bn.js@4.10.5",
      "brorand": "npm:brorand@1.0.5",
      "hash.js": "npm:hash.js@1.0.3",
      "inherits": "npm:inherits@2.0.1",
      "systemjs-json": "github:systemjs/plugin-json@0.1.0"
    },
    "npm:evp_bytestokey@1.0.0": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "create-hash": "npm:create-hash@1.1.2",
      "crypto": "github:jspm/nodelibs-crypto@0.1.0"
    },
    "npm:font-awesome@4.5.0": {
      "css": "github:systemjs/plugin-css@0.1.20"
    },
    "npm:hash.js@1.0.3": {
      "inherits": "npm:inherits@2.0.1"
    },
    "npm:inherits@2.0.1": {
      "util": "github:jspm/nodelibs-util@0.1.0"
    },
    "npm:jspdf@1.2.61": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:miller-rabin@4.0.0": {
      "bn.js": "npm:bn.js@4.10.5",
      "brorand": "npm:brorand@1.0.5"
    },
    "npm:parse-asn1@5.0.0": {
      "asn1.js": "npm:asn1.js@4.5.1",
      "browserify-aes": "npm:browserify-aes@1.0.6",
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "create-hash": "npm:create-hash@1.1.2",
      "evp_bytestokey": "npm:evp_bytestokey@1.0.0",
      "pbkdf2": "npm:pbkdf2@3.0.4",
      "systemjs-json": "github:systemjs/plugin-json@0.1.0"
    },
    "npm:path-browserify@0.0.0": {
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:pbkdf2@3.0.4": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "child_process": "github:jspm/nodelibs-child_process@0.1.0",
      "create-hmac": "npm:create-hmac@1.1.4",
      "crypto": "github:jspm/nodelibs-crypto@0.1.0",
      "path": "github:jspm/nodelibs-path@0.1.0",
      "process": "github:jspm/nodelibs-process@0.1.2",
      "systemjs-json": "github:systemjs/plugin-json@0.1.0"
    },
    "npm:process@0.11.2": {
      "assert": "github:jspm/nodelibs-assert@0.1.0"
    },
    "npm:public-encrypt@4.0.0": {
      "bn.js": "npm:bn.js@4.10.5",
      "browserify-rsa": "npm:browserify-rsa@4.0.1",
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "create-hash": "npm:create-hash@1.1.2",
      "crypto": "github:jspm/nodelibs-crypto@0.1.0",
      "parse-asn1": "npm:parse-asn1@5.0.0",
      "randombytes": "npm:randombytes@2.0.2"
    },
    "npm:randombytes@2.0.2": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "crypto": "github:jspm/nodelibs-crypto@0.1.0",
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:readable-stream@1.1.13": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "core-util-is": "npm:core-util-is@1.0.2",
      "events": "github:jspm/nodelibs-events@0.1.1",
      "inherits": "npm:inherits@2.0.1",
      "isarray": "npm:isarray@0.0.1",
      "process": "github:jspm/nodelibs-process@0.1.2",
      "stream-browserify": "npm:stream-browserify@1.0.0",
      "string_decoder": "npm:string_decoder@0.10.31"
    },
    "npm:ripemd160@1.0.1": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:sha.js@2.4.5": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "fs": "github:jspm/nodelibs-fs@0.1.2",
      "inherits": "npm:inherits@2.0.1",
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:stream-browserify@1.0.0": {
      "events": "github:jspm/nodelibs-events@0.1.1",
      "inherits": "npm:inherits@2.0.1",
      "readable-stream": "npm:readable-stream@1.1.13"
    },
    "npm:string_decoder@0.10.31": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0"
    },
    "npm:util@0.10.3": {
      "inherits": "npm:inherits@2.0.1",
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:vm-browserify@0.0.4": {
      "indexof": "npm:indexof@0.0.1"
    }
  },
  bundles: {
    "app-build-8e3f711784.js": [
      "about.html!github:systemjs/plugin-text@0.0.3.js",
      "about.js",
      "app.html!github:systemjs/plugin-text@0.0.3.js",
      "app.js",
      "blog.html!github:systemjs/plugin-text@0.0.3.js",
      "blog.js",
      "contact.html!github:systemjs/plugin-text@0.0.3.js",
      "contact.js",
      "diploma.html!github:systemjs/plugin-text@0.0.3.js",
      "diploma.js",
      "donate.html!github:systemjs/plugin-text@0.0.3.js",
      "donate.js",
      "faq.html!github:systemjs/plugin-text@0.0.3.js",
      "faq.js",
      "footer-elem.html!github:systemjs/plugin-text@0.0.3.js",
      "header-elem.html!github:systemjs/plugin-text@0.0.3.js",
      "index.html!github:systemjs/plugin-text@0.0.3.js",
      "index.js",
      "main.js",
      "partners.html!github:systemjs/plugin-text@0.0.3.js",
      "partners.js",
      "support-router.html!github:systemjs/plugin-text@0.0.3.js",
      "support-router.js",
      "terms-router.html!github:systemjs/plugin-text@0.0.3.js",
      "terms-router.js"
    ],
    "aurelia-017fffdd33.js": [
      "github:components/jquery@2.2.0.js",
      "github:components/jquery@2.2.0/jquery.js",
      "github:guillaumepotier/Parsley.js@2.3.4.js",
      "github:guillaumepotier/Parsley.js@2.3.4/dist/parsley.js",
      "github:itmcdev/aurelia-google-recaptcha@master.js",
      "github:itmcdev/aurelia-google-recaptcha@master/index.js",
      "github:jspm/nodelibs-process@0.1.2.js",
      "github:jspm/nodelibs-process@0.1.2/index.js",
      "github:twbs/bootstrap@3.3.6.js",
      "github:twbs/bootstrap@3.3.6/css/bootstrap.css!github:systemjs/plugin-text@0.0.3.js",
      "github:twbs/bootstrap@3.3.6/js/bootstrap.js",
      "npm:aurelia-animator-css@1.0.0-beta.1.0.3.js",
      "npm:aurelia-animator-css@1.0.0-beta.1.0.3/aurelia-animator-css.js",
      "npm:aurelia-binding@1.0.0-beta.1.1.3.js",
      "npm:aurelia-binding@1.0.0-beta.1.1.3/aurelia-binding.js",
      "npm:aurelia-bootstrapper@1.0.0-beta.1.0.2.js",
      "npm:aurelia-bootstrapper@1.0.0-beta.1.0.2/aurelia-bootstrapper.js",
      "npm:aurelia-dependency-injection@1.0.0-beta.1.1.3.js",
      "npm:aurelia-dependency-injection@1.0.0-beta.1.1.3/aurelia-dependency-injection.js",
      "npm:aurelia-event-aggregator@1.0.0-beta.1.js",
      "npm:aurelia-event-aggregator@1.0.0-beta.1/aurelia-event-aggregator.js",
      "npm:aurelia-fetch-client@1.0.0-beta.1.0.2.js",
      "npm:aurelia-fetch-client@1.0.0-beta.1.0.2/aurelia-fetch-client.js",
      "npm:aurelia-framework@1.0.0-beta.1.1.3.js",
      "npm:aurelia-framework@1.0.0-beta.1.1.3/aurelia-framework.js",
      "npm:aurelia-history-browser@1.0.0-beta.1.0.1.js",
      "npm:aurelia-history-browser@1.0.0-beta.1.0.1/aurelia-history-browser.js",
      "npm:aurelia-history@1.0.0-beta.1.js",
      "npm:aurelia-history@1.0.0-beta.1/aurelia-history.js",
      "npm:aurelia-loader-default@1.0.0-beta.1.0.2.js",
      "npm:aurelia-loader-default@1.0.0-beta.1.0.2/aurelia-loader-default.js",
      "npm:aurelia-loader@1.0.0-beta.1.1.1.js",
      "npm:aurelia-loader@1.0.0-beta.1.1.1/aurelia-loader.js",
      "npm:aurelia-logging-console@1.0.0-beta.1.js",
      "npm:aurelia-logging-console@1.0.0-beta.1/aurelia-logging-console.js",
      "npm:aurelia-logging@1.0.0-beta.1.1.1.js",
      "npm:aurelia-logging@1.0.0-beta.1.1.1/aurelia-logging.js",
      "npm:aurelia-metadata@1.0.0-beta.1.1.4.js",
      "npm:aurelia-metadata@1.0.0-beta.1.1.4/aurelia-metadata.js",
      "npm:aurelia-pal-browser@1.0.0-beta.1.0.3.js",
      "npm:aurelia-pal-browser@1.0.0-beta.1.0.3/aurelia-pal-browser.js",
      "npm:aurelia-pal@1.0.0-beta.1.1.1.js",
      "npm:aurelia-pal@1.0.0-beta.1.1.1/aurelia-pal.js",
      "npm:aurelia-path@1.0.0-beta.1.1.0.js",
      "npm:aurelia-path@1.0.0-beta.1.1.0/aurelia-path.js",
      "npm:aurelia-route-recognizer@1.0.0-beta.1.js",
      "npm:aurelia-route-recognizer@1.0.0-beta.1/aurelia-route-recognizer.js",
      "npm:aurelia-router@1.0.0-beta.1.0.1.js",
      "npm:aurelia-router@1.0.0-beta.1.0.1/aurelia-router.js",
      "npm:aurelia-task-queue@1.0.0-beta.1.1.1.js",
      "npm:aurelia-task-queue@1.0.0-beta.1.1.1/aurelia-task-queue.js",
      "npm:aurelia-templating-binding@1.0.0-beta.1.0.2.js",
      "npm:aurelia-templating-binding@1.0.0-beta.1.0.2/aurelia-templating-binding.js",
      "npm:aurelia-templating-resources@1.0.0-beta.1.0.4.js",
      "npm:aurelia-templating-resources@1.0.0-beta.1.0.4/analyze-view-factory.js",
      "npm:aurelia-templating-resources@1.0.0-beta.1.0.4/array-repeat-strategy.js",
      "npm:aurelia-templating-resources@1.0.0-beta.1.0.4/aurelia-templating-resources.js",
      "npm:aurelia-templating-resources@1.0.0-beta.1.0.4/binding-mode-behaviors.js",
      "npm:aurelia-templating-resources@1.0.0-beta.1.0.4/binding-signaler.js",
      "npm:aurelia-templating-resources@1.0.0-beta.1.0.4/compile-spy.js",
      "npm:aurelia-templating-resources@1.0.0-beta.1.0.4/compose.js",
      "npm:aurelia-templating-resources@1.0.0-beta.1.0.4/css-resource.js",
      "npm:aurelia-templating-resources@1.0.0-beta.1.0.4/debounce-binding-behavior.js",
      "npm:aurelia-templating-resources@1.0.0-beta.1.0.4/dynamic-element.js",
      "npm:aurelia-templating-resources@1.0.0-beta.1.0.4/focus.js",
      "npm:aurelia-templating-resources@1.0.0-beta.1.0.4/html-sanitizer.js",
      "npm:aurelia-templating-resources@1.0.0-beta.1.0.4/if.js",
      "npm:aurelia-templating-resources@1.0.0-beta.1.0.4/map-repeat-strategy.js",
      "npm:aurelia-templating-resources@1.0.0-beta.1.0.4/null-repeat-strategy.js",
      "npm:aurelia-templating-resources@1.0.0-beta.1.0.4/number-repeat-strategy.js",
      "npm:aurelia-templating-resources@1.0.0-beta.1.0.4/repeat-strategy-locator.js",
      "npm:aurelia-templating-resources@1.0.0-beta.1.0.4/repeat-utilities.js",
      "npm:aurelia-templating-resources@1.0.0-beta.1.0.4/repeat.js",
      "npm:aurelia-templating-resources@1.0.0-beta.1.0.4/replaceable.js",
      "npm:aurelia-templating-resources@1.0.0-beta.1.0.4/sanitize-html.js",
      "npm:aurelia-templating-resources@1.0.0-beta.1.0.4/set-repeat-strategy.js",
      "npm:aurelia-templating-resources@1.0.0-beta.1.0.4/show.js",
      "npm:aurelia-templating-resources@1.0.0-beta.1.0.4/signal-binding-behavior.js",
      "npm:aurelia-templating-resources@1.0.0-beta.1.0.4/throttle-binding-behavior.js",
      "npm:aurelia-templating-resources@1.0.0-beta.1.0.4/update-trigger-binding-behavior.js",
      "npm:aurelia-templating-resources@1.0.0-beta.1.0.4/view-spy.js",
      "npm:aurelia-templating-resources@1.0.0-beta.1.0.4/with.js",
      "npm:aurelia-templating-router@1.0.0-beta.1.0.5.js",
      "npm:aurelia-templating-router@1.0.0-beta.1.0.5/aurelia-templating-router.js",
      "npm:aurelia-templating-router@1.0.0-beta.1.0.5/route-href.js",
      "npm:aurelia-templating-router@1.0.0-beta.1.0.5/route-loader.js",
      "npm:aurelia-templating-router@1.0.0-beta.1.0.5/router-view.js",
      "npm:aurelia-templating@1.0.0-beta.1.1.1.js",
      "npm:aurelia-templating@1.0.0-beta.1.1.1/aurelia-templating.js",
      "npm:core-js@1.2.6.js",
      "npm:core-js@1.2.6/index.js",
      "npm:core-js@1.2.6/modules/$.a-function.js",
      "npm:core-js@1.2.6/modules/$.add-to-unscopables.js",
      "npm:core-js@1.2.6/modules/$.an-object.js",
      "npm:core-js@1.2.6/modules/$.array-copy-within.js",
      "npm:core-js@1.2.6/modules/$.array-fill.js",
      "npm:core-js@1.2.6/modules/$.array-includes.js",
      "npm:core-js@1.2.6/modules/$.array-methods.js",
      "npm:core-js@1.2.6/modules/$.array-species-create.js",
      "npm:core-js@1.2.6/modules/$.classof.js",
      "npm:core-js@1.2.6/modules/$.cof.js",
      "npm:core-js@1.2.6/modules/$.collection-strong.js",
      "npm:core-js@1.2.6/modules/$.collection-to-json.js",
      "npm:core-js@1.2.6/modules/$.collection-weak.js",
      "npm:core-js@1.2.6/modules/$.collection.js",
      "npm:core-js@1.2.6/modules/$.core.js",
      "npm:core-js@1.2.6/modules/$.ctx.js",
      "npm:core-js@1.2.6/modules/$.defined.js",
      "npm:core-js@1.2.6/modules/$.descriptors.js",
      "npm:core-js@1.2.6/modules/$.dom-create.js",
      "npm:core-js@1.2.6/modules/$.enum-keys.js",
      "npm:core-js@1.2.6/modules/$.export.js",
      "npm:core-js@1.2.6/modules/$.fails-is-regexp.js",
      "npm:core-js@1.2.6/modules/$.fails.js",
      "npm:core-js@1.2.6/modules/$.fix-re-wks.js",
      "npm:core-js@1.2.6/modules/$.flags.js",
      "npm:core-js@1.2.6/modules/$.for-of.js",
      "npm:core-js@1.2.6/modules/$.get-names.js",
      "npm:core-js@1.2.6/modules/$.global.js",
      "npm:core-js@1.2.6/modules/$.has.js",
      "npm:core-js@1.2.6/modules/$.hide.js",
      "npm:core-js@1.2.6/modules/$.html.js",
      "npm:core-js@1.2.6/modules/$.invoke.js",
      "npm:core-js@1.2.6/modules/$.iobject.js",
      "npm:core-js@1.2.6/modules/$.is-array-iter.js",
      "npm:core-js@1.2.6/modules/$.is-array.js",
      "npm:core-js@1.2.6/modules/$.is-integer.js",
      "npm:core-js@1.2.6/modules/$.is-object.js",
      "npm:core-js@1.2.6/modules/$.is-regexp.js",
      "npm:core-js@1.2.6/modules/$.iter-call.js",
      "npm:core-js@1.2.6/modules/$.iter-create.js",
      "npm:core-js@1.2.6/modules/$.iter-define.js",
      "npm:core-js@1.2.6/modules/$.iter-detect.js",
      "npm:core-js@1.2.6/modules/$.iter-step.js",
      "npm:core-js@1.2.6/modules/$.iterators.js",
      "npm:core-js@1.2.6/modules/$.js",
      "npm:core-js@1.2.6/modules/$.keyof.js",
      "npm:core-js@1.2.6/modules/$.library.js",
      "npm:core-js@1.2.6/modules/$.math-expm1.js",
      "npm:core-js@1.2.6/modules/$.math-log1p.js",
      "npm:core-js@1.2.6/modules/$.math-sign.js",
      "npm:core-js@1.2.6/modules/$.microtask.js",
      "npm:core-js@1.2.6/modules/$.object-assign.js",
      "npm:core-js@1.2.6/modules/$.object-define.js",
      "npm:core-js@1.2.6/modules/$.object-sap.js",
      "npm:core-js@1.2.6/modules/$.object-to-array.js",
      "npm:core-js@1.2.6/modules/$.own-keys.js",
      "npm:core-js@1.2.6/modules/$.partial.js",
      "npm:core-js@1.2.6/modules/$.path.js",
      "npm:core-js@1.2.6/modules/$.property-desc.js",
      "npm:core-js@1.2.6/modules/$.redefine-all.js",
      "npm:core-js@1.2.6/modules/$.redefine.js",
      "npm:core-js@1.2.6/modules/$.replacer.js",
      "npm:core-js@1.2.6/modules/$.same-value.js",
      "npm:core-js@1.2.6/modules/$.set-proto.js",
      "npm:core-js@1.2.6/modules/$.set-species.js",
      "npm:core-js@1.2.6/modules/$.set-to-string-tag.js",
      "npm:core-js@1.2.6/modules/$.shared.js",
      "npm:core-js@1.2.6/modules/$.species-constructor.js",
      "npm:core-js@1.2.6/modules/$.strict-new.js",
      "npm:core-js@1.2.6/modules/$.string-at.js",
      "npm:core-js@1.2.6/modules/$.string-context.js",
      "npm:core-js@1.2.6/modules/$.string-pad.js",
      "npm:core-js@1.2.6/modules/$.string-repeat.js",
      "npm:core-js@1.2.6/modules/$.string-trim.js",
      "npm:core-js@1.2.6/modules/$.task.js",
      "npm:core-js@1.2.6/modules/$.to-index.js",
      "npm:core-js@1.2.6/modules/$.to-integer.js",
      "npm:core-js@1.2.6/modules/$.to-iobject.js",
      "npm:core-js@1.2.6/modules/$.to-length.js",
      "npm:core-js@1.2.6/modules/$.to-object.js",
      "npm:core-js@1.2.6/modules/$.to-primitive.js",
      "npm:core-js@1.2.6/modules/$.uid.js",
      "npm:core-js@1.2.6/modules/$.wks.js",
      "npm:core-js@1.2.6/modules/core.delay.js",
      "npm:core-js@1.2.6/modules/core.dict.js",
      "npm:core-js@1.2.6/modules/core.function.part.js",
      "npm:core-js@1.2.6/modules/core.get-iterator-method.js",
      "npm:core-js@1.2.6/modules/core.get-iterator.js",
      "npm:core-js@1.2.6/modules/core.is-iterable.js",
      "npm:core-js@1.2.6/modules/core.log.js",
      "npm:core-js@1.2.6/modules/core.number.iterator.js",
      "npm:core-js@1.2.6/modules/core.object.classof.js",
      "npm:core-js@1.2.6/modules/core.object.define.js",
      "npm:core-js@1.2.6/modules/core.object.is-object.js",
      "npm:core-js@1.2.6/modules/core.object.make.js",
      "npm:core-js@1.2.6/modules/core.string.escape-html.js",
      "npm:core-js@1.2.6/modules/core.string.unescape-html.js",
      "npm:core-js@1.2.6/modules/es5.js",
      "npm:core-js@1.2.6/modules/es6.array.copy-within.js",
      "npm:core-js@1.2.6/modules/es6.array.fill.js",
      "npm:core-js@1.2.6/modules/es6.array.find-index.js",
      "npm:core-js@1.2.6/modules/es6.array.find.js",
      "npm:core-js@1.2.6/modules/es6.array.from.js",
      "npm:core-js@1.2.6/modules/es6.array.iterator.js",
      "npm:core-js@1.2.6/modules/es6.array.of.js",
      "npm:core-js@1.2.6/modules/es6.array.species.js",
      "npm:core-js@1.2.6/modules/es6.function.has-instance.js",
      "npm:core-js@1.2.6/modules/es6.function.name.js",
      "npm:core-js@1.2.6/modules/es6.map.js",
      "npm:core-js@1.2.6/modules/es6.math.acosh.js",
      "npm:core-js@1.2.6/modules/es6.math.asinh.js",
      "npm:core-js@1.2.6/modules/es6.math.atanh.js",
      "npm:core-js@1.2.6/modules/es6.math.cbrt.js",
      "npm:core-js@1.2.6/modules/es6.math.clz32.js",
      "npm:core-js@1.2.6/modules/es6.math.cosh.js",
      "npm:core-js@1.2.6/modules/es6.math.expm1.js",
      "npm:core-js@1.2.6/modules/es6.math.fround.js",
      "npm:core-js@1.2.6/modules/es6.math.hypot.js",
      "npm:core-js@1.2.6/modules/es6.math.imul.js",
      "npm:core-js@1.2.6/modules/es6.math.log10.js",
      "npm:core-js@1.2.6/modules/es6.math.log1p.js",
      "npm:core-js@1.2.6/modules/es6.math.log2.js",
      "npm:core-js@1.2.6/modules/es6.math.sign.js",
      "npm:core-js@1.2.6/modules/es6.math.sinh.js",
      "npm:core-js@1.2.6/modules/es6.math.tanh.js",
      "npm:core-js@1.2.6/modules/es6.math.trunc.js",
      "npm:core-js@1.2.6/modules/es6.number.constructor.js",
      "npm:core-js@1.2.6/modules/es6.number.epsilon.js",
      "npm:core-js@1.2.6/modules/es6.number.is-finite.js",
      "npm:core-js@1.2.6/modules/es6.number.is-integer.js",
      "npm:core-js@1.2.6/modules/es6.number.is-nan.js",
      "npm:core-js@1.2.6/modules/es6.number.is-safe-integer.js",
      "npm:core-js@1.2.6/modules/es6.number.max-safe-integer.js",
      "npm:core-js@1.2.6/modules/es6.number.min-safe-integer.js",
      "npm:core-js@1.2.6/modules/es6.number.parse-float.js",
      "npm:core-js@1.2.6/modules/es6.number.parse-int.js",
      "npm:core-js@1.2.6/modules/es6.object.assign.js",
      "npm:core-js@1.2.6/modules/es6.object.freeze.js",
      "npm:core-js@1.2.6/modules/es6.object.get-own-property-descriptor.js",
      "npm:core-js@1.2.6/modules/es6.object.get-own-property-names.js",
      "npm:core-js@1.2.6/modules/es6.object.get-prototype-of.js",
      "npm:core-js@1.2.6/modules/es6.object.is-extensible.js",
      "npm:core-js@1.2.6/modules/es6.object.is-frozen.js",
      "npm:core-js@1.2.6/modules/es6.object.is-sealed.js",
      "npm:core-js@1.2.6/modules/es6.object.is.js",
      "npm:core-js@1.2.6/modules/es6.object.keys.js",
      "npm:core-js@1.2.6/modules/es6.object.prevent-extensions.js",
      "npm:core-js@1.2.6/modules/es6.object.seal.js",
      "npm:core-js@1.2.6/modules/es6.object.set-prototype-of.js",
      "npm:core-js@1.2.6/modules/es6.object.to-string.js",
      "npm:core-js@1.2.6/modules/es6.promise.js",
      "npm:core-js@1.2.6/modules/es6.reflect.apply.js",
      "npm:core-js@1.2.6/modules/es6.reflect.construct.js",
      "npm:core-js@1.2.6/modules/es6.reflect.define-property.js",
      "npm:core-js@1.2.6/modules/es6.reflect.delete-property.js",
      "npm:core-js@1.2.6/modules/es6.reflect.enumerate.js",
      "npm:core-js@1.2.6/modules/es6.reflect.get-own-property-descriptor.js",
      "npm:core-js@1.2.6/modules/es6.reflect.get-prototype-of.js",
      "npm:core-js@1.2.6/modules/es6.reflect.get.js",
      "npm:core-js@1.2.6/modules/es6.reflect.has.js",
      "npm:core-js@1.2.6/modules/es6.reflect.is-extensible.js",
      "npm:core-js@1.2.6/modules/es6.reflect.own-keys.js",
      "npm:core-js@1.2.6/modules/es6.reflect.prevent-extensions.js",
      "npm:core-js@1.2.6/modules/es6.reflect.set-prototype-of.js",
      "npm:core-js@1.2.6/modules/es6.reflect.set.js",
      "npm:core-js@1.2.6/modules/es6.regexp.constructor.js",
      "npm:core-js@1.2.6/modules/es6.regexp.flags.js",
      "npm:core-js@1.2.6/modules/es6.regexp.match.js",
      "npm:core-js@1.2.6/modules/es6.regexp.replace.js",
      "npm:core-js@1.2.6/modules/es6.regexp.search.js",
      "npm:core-js@1.2.6/modules/es6.regexp.split.js",
      "npm:core-js@1.2.6/modules/es6.set.js",
      "npm:core-js@1.2.6/modules/es6.string.code-point-at.js",
      "npm:core-js@1.2.6/modules/es6.string.ends-with.js",
      "npm:core-js@1.2.6/modules/es6.string.from-code-point.js",
      "npm:core-js@1.2.6/modules/es6.string.includes.js",
      "npm:core-js@1.2.6/modules/es6.string.iterator.js",
      "npm:core-js@1.2.6/modules/es6.string.raw.js",
      "npm:core-js@1.2.6/modules/es6.string.repeat.js",
      "npm:core-js@1.2.6/modules/es6.string.starts-with.js",
      "npm:core-js@1.2.6/modules/es6.string.trim.js",
      "npm:core-js@1.2.6/modules/es6.symbol.js",
      "npm:core-js@1.2.6/modules/es6.weak-map.js",
      "npm:core-js@1.2.6/modules/es6.weak-set.js",
      "npm:core-js@1.2.6/modules/es7.array.includes.js",
      "npm:core-js@1.2.6/modules/es7.map.to-json.js",
      "npm:core-js@1.2.6/modules/es7.object.entries.js",
      "npm:core-js@1.2.6/modules/es7.object.get-own-property-descriptors.js",
      "npm:core-js@1.2.6/modules/es7.object.values.js",
      "npm:core-js@1.2.6/modules/es7.regexp.escape.js",
      "npm:core-js@1.2.6/modules/es7.set.to-json.js",
      "npm:core-js@1.2.6/modules/es7.string.at.js",
      "npm:core-js@1.2.6/modules/es7.string.pad-left.js",
      "npm:core-js@1.2.6/modules/es7.string.pad-right.js",
      "npm:core-js@1.2.6/modules/es7.string.trim-left.js",
      "npm:core-js@1.2.6/modules/es7.string.trim-right.js",
      "npm:core-js@1.2.6/modules/js.array.statics.js",
      "npm:core-js@1.2.6/modules/web.dom.iterable.js",
      "npm:core-js@1.2.6/modules/web.immediate.js",
      "npm:core-js@1.2.6/modules/web.timers.js",
      "npm:core-js@1.2.6/shim.js",
      "npm:core-js@2.1.1.js",
      "npm:core-js@2.1.1/index.js",
      "npm:core-js@2.1.1/modules/_a-function.js",
      "npm:core-js@2.1.1/modules/_a-number-value.js",
      "npm:core-js@2.1.1/modules/_add-to-unscopables.js",
      "npm:core-js@2.1.1/modules/_an-instance.js",
      "npm:core-js@2.1.1/modules/_an-object.js",
      "npm:core-js@2.1.1/modules/_array-copy-within.js",
      "npm:core-js@2.1.1/modules/_array-fill.js",
      "npm:core-js@2.1.1/modules/_array-from-iterable.js",
      "npm:core-js@2.1.1/modules/_array-includes.js",
      "npm:core-js@2.1.1/modules/_array-methods.js",
      "npm:core-js@2.1.1/modules/_array-reduce.js",
      "npm:core-js@2.1.1/modules/_array-species-create.js",
      "npm:core-js@2.1.1/modules/_bind.js",
      "npm:core-js@2.1.1/modules/_classof.js",
      "npm:core-js@2.1.1/modules/_cof.js",
      "npm:core-js@2.1.1/modules/_collection-strong.js",
      "npm:core-js@2.1.1/modules/_collection-to-json.js",
      "npm:core-js@2.1.1/modules/_collection-weak.js",
      "npm:core-js@2.1.1/modules/_collection.js",
      "npm:core-js@2.1.1/modules/_core.js",
      "npm:core-js@2.1.1/modules/_ctx.js",
      "npm:core-js@2.1.1/modules/_defined.js",
      "npm:core-js@2.1.1/modules/_descriptors.js",
      "npm:core-js@2.1.1/modules/_dom-create.js",
      "npm:core-js@2.1.1/modules/_enum-bug-keys.js",
      "npm:core-js@2.1.1/modules/_enum-keys.js",
      "npm:core-js@2.1.1/modules/_export.js",
      "npm:core-js@2.1.1/modules/_fails-is-regexp.js",
      "npm:core-js@2.1.1/modules/_fails.js",
      "npm:core-js@2.1.1/modules/_fix-re-wks.js",
      "npm:core-js@2.1.1/modules/_flags.js",
      "npm:core-js@2.1.1/modules/_for-of.js",
      "npm:core-js@2.1.1/modules/_global.js",
      "npm:core-js@2.1.1/modules/_has.js",
      "npm:core-js@2.1.1/modules/_hide.js",
      "npm:core-js@2.1.1/modules/_html.js",
      "npm:core-js@2.1.1/modules/_ie8-dom-define.js",
      "npm:core-js@2.1.1/modules/_inherit-if-required.js",
      "npm:core-js@2.1.1/modules/_invoke.js",
      "npm:core-js@2.1.1/modules/_iobject.js",
      "npm:core-js@2.1.1/modules/_is-array-iter.js",
      "npm:core-js@2.1.1/modules/_is-array.js",
      "npm:core-js@2.1.1/modules/_is-integer.js",
      "npm:core-js@2.1.1/modules/_is-object.js",
      "npm:core-js@2.1.1/modules/_is-regexp.js",
      "npm:core-js@2.1.1/modules/_iter-call.js",
      "npm:core-js@2.1.1/modules/_iter-create.js",
      "npm:core-js@2.1.1/modules/_iter-define.js",
      "npm:core-js@2.1.1/modules/_iter-detect.js",
      "npm:core-js@2.1.1/modules/_iter-step.js",
      "npm:core-js@2.1.1/modules/_iterators.js",
      "npm:core-js@2.1.1/modules/_keyof.js",
      "npm:core-js@2.1.1/modules/_library.js",
      "npm:core-js@2.1.1/modules/_math-expm1.js",
      "npm:core-js@2.1.1/modules/_math-log1p.js",
      "npm:core-js@2.1.1/modules/_math-sign.js",
      "npm:core-js@2.1.1/modules/_meta.js",
      "npm:core-js@2.1.1/modules/_metadata.js",
      "npm:core-js@2.1.1/modules/_microtask.js",
      "npm:core-js@2.1.1/modules/_object-assign.js",
      "npm:core-js@2.1.1/modules/_object-create.js",
      "npm:core-js@2.1.1/modules/_object-define.js",
      "npm:core-js@2.1.1/modules/_object-dp.js",
      "npm:core-js@2.1.1/modules/_object-dps.js",
      "npm:core-js@2.1.1/modules/_object-gopd.js",
      "npm:core-js@2.1.1/modules/_object-gopn-ext.js",
      "npm:core-js@2.1.1/modules/_object-gopn.js",
      "npm:core-js@2.1.1/modules/_object-gops.js",
      "npm:core-js@2.1.1/modules/_object-gpo.js",
      "npm:core-js@2.1.1/modules/_object-keys-internal.js",
      "npm:core-js@2.1.1/modules/_object-keys.js",
      "npm:core-js@2.1.1/modules/_object-pie.js",
      "npm:core-js@2.1.1/modules/_object-sap.js",
      "npm:core-js@2.1.1/modules/_object-to-array.js",
      "npm:core-js@2.1.1/modules/_own-keys.js",
      "npm:core-js@2.1.1/modules/_parse-float.js",
      "npm:core-js@2.1.1/modules/_parse-int.js",
      "npm:core-js@2.1.1/modules/_partial.js",
      "npm:core-js@2.1.1/modules/_path.js",
      "npm:core-js@2.1.1/modules/_property-desc.js",
      "npm:core-js@2.1.1/modules/_redefine-all.js",
      "npm:core-js@2.1.1/modules/_redefine.js",
      "npm:core-js@2.1.1/modules/_replacer.js",
      "npm:core-js@2.1.1/modules/_same-value.js",
      "npm:core-js@2.1.1/modules/_set-proto.js",
      "npm:core-js@2.1.1/modules/_set-species.js",
      "npm:core-js@2.1.1/modules/_set-to-string-tag.js",
      "npm:core-js@2.1.1/modules/_shared-key.js",
      "npm:core-js@2.1.1/modules/_shared.js",
      "npm:core-js@2.1.1/modules/_species-constructor.js",
      "npm:core-js@2.1.1/modules/_strict-method.js",
      "npm:core-js@2.1.1/modules/_string-at.js",
      "npm:core-js@2.1.1/modules/_string-context.js",
      "npm:core-js@2.1.1/modules/_string-html.js",
      "npm:core-js@2.1.1/modules/_string-pad.js",
      "npm:core-js@2.1.1/modules/_string-repeat.js",
      "npm:core-js@2.1.1/modules/_string-trim.js",
      "npm:core-js@2.1.1/modules/_string-ws.js",
      "npm:core-js@2.1.1/modules/_task.js",
      "npm:core-js@2.1.1/modules/_to-index.js",
      "npm:core-js@2.1.1/modules/_to-integer.js",
      "npm:core-js@2.1.1/modules/_to-iobject.js",
      "npm:core-js@2.1.1/modules/_to-length.js",
      "npm:core-js@2.1.1/modules/_to-object.js",
      "npm:core-js@2.1.1/modules/_to-primitive.js",
      "npm:core-js@2.1.1/modules/_typed-array.js",
      "npm:core-js@2.1.1/modules/_typed-buffer.js",
      "npm:core-js@2.1.1/modules/_typed.js",
      "npm:core-js@2.1.1/modules/_uid.js",
      "npm:core-js@2.1.1/modules/_wks.js",
      "npm:core-js@2.1.1/modules/core.delay.js",
      "npm:core-js@2.1.1/modules/core.dict.js",
      "npm:core-js@2.1.1/modules/core.function.part.js",
      "npm:core-js@2.1.1/modules/core.get-iterator-method.js",
      "npm:core-js@2.1.1/modules/core.get-iterator.js",
      "npm:core-js@2.1.1/modules/core.is-iterable.js",
      "npm:core-js@2.1.1/modules/core.number.iterator.js",
      "npm:core-js@2.1.1/modules/core.object.classof.js",
      "npm:core-js@2.1.1/modules/core.object.define.js",
      "npm:core-js@2.1.1/modules/core.object.is-object.js",
      "npm:core-js@2.1.1/modules/core.object.make.js",
      "npm:core-js@2.1.1/modules/core.regexp.escape.js",
      "npm:core-js@2.1.1/modules/core.string.escape-html.js",
      "npm:core-js@2.1.1/modules/core.string.unescape-html.js",
      "npm:core-js@2.1.1/modules/es6.array.copy-within.js",
      "npm:core-js@2.1.1/modules/es6.array.every.js",
      "npm:core-js@2.1.1/modules/es6.array.fill.js",
      "npm:core-js@2.1.1/modules/es6.array.filter.js",
      "npm:core-js@2.1.1/modules/es6.array.find-index.js",
      "npm:core-js@2.1.1/modules/es6.array.find.js",
      "npm:core-js@2.1.1/modules/es6.array.for-each.js",
      "npm:core-js@2.1.1/modules/es6.array.from.js",
      "npm:core-js@2.1.1/modules/es6.array.index-of.js",
      "npm:core-js@2.1.1/modules/es6.array.is-array.js",
      "npm:core-js@2.1.1/modules/es6.array.iterator.js",
      "npm:core-js@2.1.1/modules/es6.array.join.js",
      "npm:core-js@2.1.1/modules/es6.array.last-index-of.js",
      "npm:core-js@2.1.1/modules/es6.array.map.js",
      "npm:core-js@2.1.1/modules/es6.array.of.js",
      "npm:core-js@2.1.1/modules/es6.array.reduce-right.js",
      "npm:core-js@2.1.1/modules/es6.array.reduce.js",
      "npm:core-js@2.1.1/modules/es6.array.slice.js",
      "npm:core-js@2.1.1/modules/es6.array.some.js",
      "npm:core-js@2.1.1/modules/es6.array.sort.js",
      "npm:core-js@2.1.1/modules/es6.array.species.js",
      "npm:core-js@2.1.1/modules/es6.date.now.js",
      "npm:core-js@2.1.1/modules/es6.date.to-iso-string.js",
      "npm:core-js@2.1.1/modules/es6.date.to-json.js",
      "npm:core-js@2.1.1/modules/es6.date.to-string.js",
      "npm:core-js@2.1.1/modules/es6.function.bind.js",
      "npm:core-js@2.1.1/modules/es6.function.has-instance.js",
      "npm:core-js@2.1.1/modules/es6.function.name.js",
      "npm:core-js@2.1.1/modules/es6.map.js",
      "npm:core-js@2.1.1/modules/es6.math.acosh.js",
      "npm:core-js@2.1.1/modules/es6.math.asinh.js",
      "npm:core-js@2.1.1/modules/es6.math.atanh.js",
      "npm:core-js@2.1.1/modules/es6.math.cbrt.js",
      "npm:core-js@2.1.1/modules/es6.math.clz32.js",
      "npm:core-js@2.1.1/modules/es6.math.cosh.js",
      "npm:core-js@2.1.1/modules/es6.math.expm1.js",
      "npm:core-js@2.1.1/modules/es6.math.fround.js",
      "npm:core-js@2.1.1/modules/es6.math.hypot.js",
      "npm:core-js@2.1.1/modules/es6.math.imul.js",
      "npm:core-js@2.1.1/modules/es6.math.log10.js",
      "npm:core-js@2.1.1/modules/es6.math.log1p.js",
      "npm:core-js@2.1.1/modules/es6.math.log2.js",
      "npm:core-js@2.1.1/modules/es6.math.sign.js",
      "npm:core-js@2.1.1/modules/es6.math.sinh.js",
      "npm:core-js@2.1.1/modules/es6.math.tanh.js",
      "npm:core-js@2.1.1/modules/es6.math.trunc.js",
      "npm:core-js@2.1.1/modules/es6.number.constructor.js",
      "npm:core-js@2.1.1/modules/es6.number.epsilon.js",
      "npm:core-js@2.1.1/modules/es6.number.is-finite.js",
      "npm:core-js@2.1.1/modules/es6.number.is-integer.js",
      "npm:core-js@2.1.1/modules/es6.number.is-nan.js",
      "npm:core-js@2.1.1/modules/es6.number.is-safe-integer.js",
      "npm:core-js@2.1.1/modules/es6.number.max-safe-integer.js",
      "npm:core-js@2.1.1/modules/es6.number.min-safe-integer.js",
      "npm:core-js@2.1.1/modules/es6.number.parse-float.js",
      "npm:core-js@2.1.1/modules/es6.number.parse-int.js",
      "npm:core-js@2.1.1/modules/es6.number.to-fixed.js",
      "npm:core-js@2.1.1/modules/es6.number.to-precision.js",
      "npm:core-js@2.1.1/modules/es6.object.assign.js",
      "npm:core-js@2.1.1/modules/es6.object.create.js",
      "npm:core-js@2.1.1/modules/es6.object.define-properties.js",
      "npm:core-js@2.1.1/modules/es6.object.define-property.js",
      "npm:core-js@2.1.1/modules/es6.object.freeze.js",
      "npm:core-js@2.1.1/modules/es6.object.get-own-property-descriptor.js",
      "npm:core-js@2.1.1/modules/es6.object.get-own-property-names.js",
      "npm:core-js@2.1.1/modules/es6.object.get-prototype-of.js",
      "npm:core-js@2.1.1/modules/es6.object.is-extensible.js",
      "npm:core-js@2.1.1/modules/es6.object.is-frozen.js",
      "npm:core-js@2.1.1/modules/es6.object.is-sealed.js",
      "npm:core-js@2.1.1/modules/es6.object.is.js",
      "npm:core-js@2.1.1/modules/es6.object.keys.js",
      "npm:core-js@2.1.1/modules/es6.object.prevent-extensions.js",
      "npm:core-js@2.1.1/modules/es6.object.seal.js",
      "npm:core-js@2.1.1/modules/es6.object.set-prototype-of.js",
      "npm:core-js@2.1.1/modules/es6.object.to-string.js",
      "npm:core-js@2.1.1/modules/es6.parse-float.js",
      "npm:core-js@2.1.1/modules/es6.parse-int.js",
      "npm:core-js@2.1.1/modules/es6.promise.js",
      "npm:core-js@2.1.1/modules/es6.reflect.apply.js",
      "npm:core-js@2.1.1/modules/es6.reflect.construct.js",
      "npm:core-js@2.1.1/modules/es6.reflect.define-property.js",
      "npm:core-js@2.1.1/modules/es6.reflect.delete-property.js",
      "npm:core-js@2.1.1/modules/es6.reflect.enumerate.js",
      "npm:core-js@2.1.1/modules/es6.reflect.get-own-property-descriptor.js",
      "npm:core-js@2.1.1/modules/es6.reflect.get-prototype-of.js",
      "npm:core-js@2.1.1/modules/es6.reflect.get.js",
      "npm:core-js@2.1.1/modules/es6.reflect.has.js",
      "npm:core-js@2.1.1/modules/es6.reflect.is-extensible.js",
      "npm:core-js@2.1.1/modules/es6.reflect.own-keys.js",
      "npm:core-js@2.1.1/modules/es6.reflect.prevent-extensions.js",
      "npm:core-js@2.1.1/modules/es6.reflect.set-prototype-of.js",
      "npm:core-js@2.1.1/modules/es6.reflect.set.js",
      "npm:core-js@2.1.1/modules/es6.regexp.constructor.js",
      "npm:core-js@2.1.1/modules/es6.regexp.flags.js",
      "npm:core-js@2.1.1/modules/es6.regexp.match.js",
      "npm:core-js@2.1.1/modules/es6.regexp.replace.js",
      "npm:core-js@2.1.1/modules/es6.regexp.search.js",
      "npm:core-js@2.1.1/modules/es6.regexp.split.js",
      "npm:core-js@2.1.1/modules/es6.regexp.to-string.js",
      "npm:core-js@2.1.1/modules/es6.set.js",
      "npm:core-js@2.1.1/modules/es6.string.anchor.js",
      "npm:core-js@2.1.1/modules/es6.string.big.js",
      "npm:core-js@2.1.1/modules/es6.string.blink.js",
      "npm:core-js@2.1.1/modules/es6.string.bold.js",
      "npm:core-js@2.1.1/modules/es6.string.code-point-at.js",
      "npm:core-js@2.1.1/modules/es6.string.ends-with.js",
      "npm:core-js@2.1.1/modules/es6.string.fixed.js",
      "npm:core-js@2.1.1/modules/es6.string.fontcolor.js",
      "npm:core-js@2.1.1/modules/es6.string.fontsize.js",
      "npm:core-js@2.1.1/modules/es6.string.from-code-point.js",
      "npm:core-js@2.1.1/modules/es6.string.includes.js",
      "npm:core-js@2.1.1/modules/es6.string.italics.js",
      "npm:core-js@2.1.1/modules/es6.string.iterator.js",
      "npm:core-js@2.1.1/modules/es6.string.link.js",
      "npm:core-js@2.1.1/modules/es6.string.raw.js",
      "npm:core-js@2.1.1/modules/es6.string.repeat.js",
      "npm:core-js@2.1.1/modules/es6.string.small.js",
      "npm:core-js@2.1.1/modules/es6.string.starts-with.js",
      "npm:core-js@2.1.1/modules/es6.string.strike.js",
      "npm:core-js@2.1.1/modules/es6.string.sub.js",
      "npm:core-js@2.1.1/modules/es6.string.sup.js",
      "npm:core-js@2.1.1/modules/es6.string.trim.js",
      "npm:core-js@2.1.1/modules/es6.symbol.js",
      "npm:core-js@2.1.1/modules/es6.typed.array-buffer.js",
      "npm:core-js@2.1.1/modules/es6.typed.data-view.js",
      "npm:core-js@2.1.1/modules/es6.typed.float32-array.js",
      "npm:core-js@2.1.1/modules/es6.typed.float64-array.js",
      "npm:core-js@2.1.1/modules/es6.typed.int16-array.js",
      "npm:core-js@2.1.1/modules/es6.typed.int32-array.js",
      "npm:core-js@2.1.1/modules/es6.typed.int8-array.js",
      "npm:core-js@2.1.1/modules/es6.typed.uint16-array.js",
      "npm:core-js@2.1.1/modules/es6.typed.uint32-array.js",
      "npm:core-js@2.1.1/modules/es6.typed.uint8-array.js",
      "npm:core-js@2.1.1/modules/es6.typed.uint8-clamped-array.js",
      "npm:core-js@2.1.1/modules/es6.weak-map.js",
      "npm:core-js@2.1.1/modules/es6.weak-set.js",
      "npm:core-js@2.1.1/modules/es7.array.includes.js",
      "npm:core-js@2.1.1/modules/es7.error.is-error.js",
      "npm:core-js@2.1.1/modules/es7.map.to-json.js",
      "npm:core-js@2.1.1/modules/es7.math.iaddh.js",
      "npm:core-js@2.1.1/modules/es7.math.imulh.js",
      "npm:core-js@2.1.1/modules/es7.math.isubh.js",
      "npm:core-js@2.1.1/modules/es7.math.umulh.js",
      "npm:core-js@2.1.1/modules/es7.object.entries.js",
      "npm:core-js@2.1.1/modules/es7.object.get-own-property-descriptors.js",
      "npm:core-js@2.1.1/modules/es7.object.values.js",
      "npm:core-js@2.1.1/modules/es7.reflect.define-metadata.js",
      "npm:core-js@2.1.1/modules/es7.reflect.delete-metadata.js",
      "npm:core-js@2.1.1/modules/es7.reflect.get-metadata-keys.js",
      "npm:core-js@2.1.1/modules/es7.reflect.get-metadata.js",
      "npm:core-js@2.1.1/modules/es7.reflect.get-own-metadata-keys.js",
      "npm:core-js@2.1.1/modules/es7.reflect.get-own-metadata.js",
      "npm:core-js@2.1.1/modules/es7.reflect.has-metadata.js",
      "npm:core-js@2.1.1/modules/es7.reflect.has-own-metadata.js",
      "npm:core-js@2.1.1/modules/es7.reflect.metadata.js",
      "npm:core-js@2.1.1/modules/es7.set.to-json.js",
      "npm:core-js@2.1.1/modules/es7.string.at.js",
      "npm:core-js@2.1.1/modules/es7.string.pad-end.js",
      "npm:core-js@2.1.1/modules/es7.string.pad-start.js",
      "npm:core-js@2.1.1/modules/es7.string.trim-left.js",
      "npm:core-js@2.1.1/modules/es7.string.trim-right.js",
      "npm:core-js@2.1.1/modules/es7.system.global.js",
      "npm:core-js@2.1.1/modules/web.dom.iterable.js",
      "npm:core-js@2.1.1/modules/web.immediate.js",
      "npm:core-js@2.1.1/modules/web.timers.js",
      "npm:core-js@2.1.1/shim.js",
      "npm:process@0.11.2.js",
      "npm:process@0.11.2/browser.js"
    ]
  },
  depCache: {
    "about.js": [
      "lib/view/model/abstract"
    ],
    "app.js": [
      "aurelia-framework"
    ],
    "contact.js": [
      "aurelia-framework",
      "fetch",
      "aurelia-fetch-client",
      "lib/app/config",
      "lib/view/model/abstract",
      "parsleyjs",
      "parsleyjs/dist/i18n/ro"
    ],
    "diploma.js": [
      "aurelia-framework",
      "fetch",
      "aurelia-fetch-client",
      "jspdf",
      "lib/app/config",
      "lib/view/model/abstract"
    ],
    "donate.js": [
      "aurelia-validation",
      "aurelia-framework",
      "fetch",
      "aurelia-fetch-client",
      "lib/app/config",
      "lib/view/model/abstract",
      "bootstrap-slider",
      "parsleyjs",
      "parsleyjs/dist/i18n/ro",
      "braintree/braintree-web",
      "tsironis/lockr"
    ],
    "index.js": [
      "aurelia-framework",
      "aurelia-fetch-client",
      "fetch",
      "lib/app/config",
      "lib/view/model/abstract"
    ],
    "main.js": [
      "bootstrap"
    ],
    "partners.js": [
      "aurelia-framework",
      "aurelia-fetch-client",
      "fetch",
      "lib/app/config",
      "lib/view/model/abstract",
      "lib/value-converters/array/shuffle.js"
    ],
    "support-router.js": [
      "lib/view/model/abstract"
    ],
    "terms-router.js": [
      "lib/view/model/abstract"
    ]
  }
});