System.config({
  defaultJSExtensions: true,
  transpiler: "babel",
  babelOptions: {
    "optional": [
      "es7.decorators",
      "es7.classProperties"
    ]
  },
  paths: {
    "*": "dist/*",
    "github:*": "jspm_packages/github/*",
    "npm:*": "jspm_packages/npm/*"
  },
  meta: {
    "../assets/plugins/revoslider/js/jquery.themepunch.tools.min.js": {
      "deps": [
        "jquery"
      ]
    }
  },
  map: {
    "aurelia-animator-css": "npm:aurelia-animator-css@1.0.0-beta.1.0.3",
    "aurelia-bootstrapper": "npm:aurelia-bootstrapper@1.0.0-beta.1.0.2",
    "aurelia-fetch-client": "npm:aurelia-fetch-client@1.0.0-beta.1.0.2",
    "aurelia-framework": "npm:aurelia-framework@1.0.0-beta.1.1.3",
    "aurelia-history-browser": "npm:aurelia-history-browser@1.0.0-beta.1.0.1",
    "aurelia-loader-default": "npm:aurelia-loader-default@1.0.0-beta.1.0.2",
    "aurelia-logging-console": "npm:aurelia-logging-console@1.0.0-beta.1",
    "aurelia-router": "npm:aurelia-router@1.0.0-beta.1.0.1",
    "aurelia-templating-binding": "npm:aurelia-templating-binding@1.0.0-beta.1.0.2",
    "aurelia-templating-resources": "npm:aurelia-templating-resources@1.0.0-beta.1.0.4",
    "aurelia-templating-router": "npm:aurelia-templating-router@1.0.0-beta.1.0.5",
    "aurelia-validation": "github:aurelia/validation@0.6.2",
    "babel": "npm:babel-core@5.8.34",
    "babel-runtime": "npm:babel-runtime@5.8.34",
    "beatgammit/base64-js": "github:beatgammit/base64-js@1.1.1",
    "bootstrap": "github:twbs/bootstrap@3.3.6",
    "bootstrap-slider": "github:seiyria/bootstrap-slider@6.0.17",
    "braintree/braintree-web": "github:braintree/braintree-web@2.21.0",
    "core-js": "npm:core-js@1.2.6",
    "dankogai/js-base64": "github:dankogai/js-base64@2.1.9",
    "fetch": "github:github/fetch@0.10.1",
    "font-awesome": "npm:font-awesome@4.5.0",
    "google-recaptcha": "github:itmcdev/aurelia-google-recaptcha@master",
    "jquery": "github:components/jquery@2.2.0",
    "jspm/nodelibs-crypto": "github:jspm/nodelibs-crypto@0.1.0",
    "parsleyjs": "github:guillaumepotier/Parsley.js@2.3.4",
    "text": "github:systemjs/plugin-text@0.0.3",
    "tsironis/lockr": "github:tsironis/lockr@0.8.4",
    "github:aurelia/validation@0.6.2": {
      "aurelia-binding": "npm:aurelia-binding@1.0.0-beta.1.1.3",
      "aurelia-dependency-injection": "npm:aurelia-dependency-injection@1.0.0-beta.1.1.3",
      "aurelia-logging": "npm:aurelia-logging@1.0.0-beta.1.1.1",
      "aurelia-metadata": "npm:aurelia-metadata@1.0.0-beta.1.1.4",
      "aurelia-templating": "npm:aurelia-templating@1.0.0-beta.1.1.1"
    },
    "github:guillaumepotier/Parsley.js@2.3.4": {
      "jquery": "github:components/jquery@2.2.0"
    },
    "github:itmcdev/aurelia-google-recaptcha@master": {
      "aurelia-framework": "npm:aurelia-framework@1.0.0-beta.1.1.3"
    },
    "github:jspm/nodelibs-assert@0.1.0": {
      "assert": "npm:assert@1.3.0"
    },
    "github:jspm/nodelibs-buffer@0.1.0": {
      "buffer": "npm:buffer@3.6.0"
    },
    "github:jspm/nodelibs-constants@0.1.0": {
      "constants-browserify": "npm:constants-browserify@0.0.1"
    },
    "github:jspm/nodelibs-crypto@0.1.0": {
      "crypto-browserify": "npm:crypto-browserify@3.11.0"
    },
    "github:jspm/nodelibs-events@0.1.1": {
      "events": "npm:events@1.0.2"
    },
    "github:jspm/nodelibs-path@0.1.0": {
      "path-browserify": "npm:path-browserify@0.0.0"
    },
    "github:jspm/nodelibs-process@0.1.2": {
      "process": "npm:process@0.11.2"
    },
    "github:jspm/nodelibs-stream@0.1.0": {
      "stream-browserify": "npm:stream-browserify@1.0.0"
    },
    "github:jspm/nodelibs-string_decoder@0.1.0": {
      "string_decoder": "npm:string_decoder@0.10.31"
    },
    "github:jspm/nodelibs-util@0.1.0": {
      "util": "npm:util@0.10.3"
    },
    "github:jspm/nodelibs-vm@0.1.0": {
      "vm-browserify": "npm:vm-browserify@0.0.4"
    },
    "github:twbs/bootstrap@3.3.6": {
      "jquery": "github:components/jquery@2.2.0"
    },
    "npm:asn1.js@4.5.1": {
      "assert": "github:jspm/nodelibs-assert@0.1.0",
      "bn.js": "npm:bn.js@4.10.5",
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "fs": "github:jspm/nodelibs-fs@0.1.2",
      "inherits": "npm:inherits@2.0.1",
      "minimalistic-assert": "npm:minimalistic-assert@1.0.0",
      "vm": "github:jspm/nodelibs-vm@0.1.0"
    },
    "npm:assert@1.3.0": {
      "util": "npm:util@0.10.3"
    },
    "npm:aurelia-animator-css@1.0.0-beta.1.0.3": {
      "aurelia-metadata": "npm:aurelia-metadata@1.0.0-beta.1.1.4",
      "aurelia-pal": "npm:aurelia-pal@1.0.0-beta.1.1.1",
      "aurelia-templating": "npm:aurelia-templating@1.0.0-beta.1.1.1"
    },
    "npm:aurelia-binding@1.0.0-beta.1.1.3": {
      "aurelia-metadata": "npm:aurelia-metadata@1.0.0-beta.1.1.4",
      "aurelia-pal": "npm:aurelia-pal@1.0.0-beta.1.1.1",
      "aurelia-task-queue": "npm:aurelia-task-queue@1.0.0-beta.1.1.1",
      "core-js": "npm:core-js@2.1.1"
    },
    "npm:aurelia-bootstrapper@1.0.0-beta.1.0.2": {
      "aurelia-event-aggregator": "npm:aurelia-event-aggregator@1.0.0-beta.1",
      "aurelia-framework": "npm:aurelia-framework@1.0.0-beta.1.1.3",
      "aurelia-history": "npm:aurelia-history@1.0.0-beta.1",
      "aurelia-history-browser": "npm:aurelia-history-browser@1.0.0-beta.1.0.1",
      "aurelia-loader-default": "npm:aurelia-loader-default@1.0.0-beta.1.0.2",
      "aurelia-logging-console": "npm:aurelia-logging-console@1.0.0-beta.1",
      "aurelia-pal": "npm:aurelia-pal@1.0.0-beta.1.1.1",
      "aurelia-pal-browser": "npm:aurelia-pal-browser@1.0.0-beta.1.0.3",
      "aurelia-router": "npm:aurelia-router@1.0.0-beta.1.0.1",
      "aurelia-templating": "npm:aurelia-templating@1.0.0-beta.1.1.1",
      "aurelia-templating-binding": "npm:aurelia-templating-binding@1.0.0-beta.1.0.2",
      "aurelia-templating-resources": "npm:aurelia-templating-resources@1.0.0-beta.1.0.4",
      "aurelia-templating-router": "npm:aurelia-templating-router@1.0.0-beta.1.0.5",
      "core-js": "npm:core-js@1.2.6"
    },
    "npm:aurelia-dependency-injection@1.0.0-beta.1.1.3": {
      "aurelia-logging": "npm:aurelia-logging@1.0.0-beta.1.1.1",
      "aurelia-metadata": "npm:aurelia-metadata@1.0.0-beta.1.1.4",
      "aurelia-pal": "npm:aurelia-pal@1.0.0-beta.1.1.1",
      "core-js": "npm:core-js@2.1.1"
    },
    "npm:aurelia-event-aggregator@1.0.0-beta.1": {
      "aurelia-logging": "npm:aurelia-logging@1.0.0-beta.1.1.1"
    },
    "npm:aurelia-fetch-client@1.0.0-beta.1.0.2": {
      "core-js": "npm:core-js@1.2.6"
    },
    "npm:aurelia-framework@1.0.0-beta.1.1.3": {
      "aurelia-binding": "npm:aurelia-binding@1.0.0-beta.1.1.3",
      "aurelia-dependency-injection": "npm:aurelia-dependency-injection@1.0.0-beta.1.1.3",
      "aurelia-loader": "npm:aurelia-loader@1.0.0-beta.1.1.1",
      "aurelia-logging": "npm:aurelia-logging@1.0.0-beta.1.1.1",
      "aurelia-metadata": "npm:aurelia-metadata@1.0.0-beta.1.1.4",
      "aurelia-pal": "npm:aurelia-pal@1.0.0-beta.1.1.1",
      "aurelia-path": "npm:aurelia-path@1.0.0-beta.1.1.0",
      "aurelia-task-queue": "npm:aurelia-task-queue@1.0.0-beta.1.1.1",
      "aurelia-templating": "npm:aurelia-templating@1.0.0-beta.1.1.1",
      "core-js": "npm:core-js@2.1.1"
    },
    "npm:aurelia-history-browser@1.0.0-beta.1.0.1": {
      "aurelia-history": "npm:aurelia-history@1.0.0-beta.1",
      "aurelia-pal": "npm:aurelia-pal@1.0.0-beta.1.1.1",
      "core-js": "npm:core-js@1.2.6"
    },
    "npm:aurelia-loader-default@1.0.0-beta.1.0.2": {
      "aurelia-loader": "npm:aurelia-loader@1.0.0-beta.1.1.1",
      "aurelia-metadata": "npm:aurelia-metadata@1.0.0-beta.1.1.4",
      "aurelia-pal": "npm:aurelia-pal@1.0.0-beta.1.1.1"
    },
    "npm:aurelia-loader@1.0.0-beta.1.1.1": {
      "aurelia-metadata": "npm:aurelia-metadata@1.0.0-beta.1.1.4",
      "aurelia-path": "npm:aurelia-path@1.0.0-beta.1.1.0"
    },
    "npm:aurelia-logging-console@1.0.0-beta.1": {
      "aurelia-logging": "npm:aurelia-logging@1.0.0-beta.1.1.1",
      "aurelia-pal": "npm:aurelia-pal@1.0.0-beta.1.1.1"
    },
    "npm:aurelia-metadata@1.0.0-beta.1.1.4": {
      "aurelia-pal": "npm:aurelia-pal@1.0.0-beta.1.1.1",
      "core-js": "npm:core-js@2.1.1"
    },
    "npm:aurelia-pal-browser@1.0.0-beta.1.0.3": {
      "aurelia-pal": "npm:aurelia-pal@1.0.0-beta.1.1.1",
      "core-js": "npm:core-js@1.2.6"
    },
    "npm:aurelia-route-recognizer@1.0.0-beta.1": {
      "aurelia-path": "npm:aurelia-path@1.0.0-beta.1.1.0",
      "core-js": "npm:core-js@1.2.6"
    },
    "npm:aurelia-router@1.0.0-beta.1.0.1": {
      "aurelia-dependency-injection": "npm:aurelia-dependency-injection@1.0.0-beta.1.1.3",
      "aurelia-event-aggregator": "npm:aurelia-event-aggregator@1.0.0-beta.1",
      "aurelia-history": "npm:aurelia-history@1.0.0-beta.1",
      "aurelia-logging": "npm:aurelia-logging@1.0.0-beta.1.1.1",
      "aurelia-path": "npm:aurelia-path@1.0.0-beta.1.1.0",
      "aurelia-route-recognizer": "npm:aurelia-route-recognizer@1.0.0-beta.1",
      "core-js": "npm:core-js@1.2.6"
    },
    "npm:aurelia-task-queue@1.0.0-beta.1.1.1": {
      "aurelia-pal": "npm:aurelia-pal@1.0.0-beta.1.1.1"
    },
    "npm:aurelia-templating-binding@1.0.0-beta.1.0.2": {
      "aurelia-binding": "npm:aurelia-binding@1.0.0-beta.1.1.3",
      "aurelia-logging": "npm:aurelia-logging@1.0.0-beta.1.1.1",
      "aurelia-templating": "npm:aurelia-templating@1.0.0-beta.1.1.1"
    },
    "npm:aurelia-templating-resources@1.0.0-beta.1.0.4": {
      "aurelia-binding": "npm:aurelia-binding@1.0.0-beta.1.1.3",
      "aurelia-dependency-injection": "npm:aurelia-dependency-injection@1.0.0-beta.1.1.3",
      "aurelia-loader": "npm:aurelia-loader@1.0.0-beta.1.1.1",
      "aurelia-logging": "npm:aurelia-logging@1.0.0-beta.1.1.1",
      "aurelia-pal": "npm:aurelia-pal@1.0.0-beta.1.1.1",
      "aurelia-path": "npm:aurelia-path@1.0.0-beta.1.1.0",
      "aurelia-task-queue": "npm:aurelia-task-queue@1.0.0-beta.1.1.1",
      "aurelia-templating": "npm:aurelia-templating@1.0.0-beta.1.1.1",
      "core-js": "npm:core-js@1.2.6"
    },
    "npm:aurelia-templating-router@1.0.0-beta.1.0.5": {
      "aurelia-dependency-injection": "npm:aurelia-dependency-injection@1.0.0-beta.1.1.3",
      "aurelia-logging": "npm:aurelia-logging@1.0.0-beta.1.1.1",
      "aurelia-metadata": "npm:aurelia-metadata@1.0.0-beta.1.1.4",
      "aurelia-pal": "npm:aurelia-pal@1.0.0-beta.1.1.1",
      "aurelia-path": "npm:aurelia-path@1.0.0-beta.1.1.0",
      "aurelia-router": "npm:aurelia-router@1.0.0-beta.1.0.1",
      "aurelia-templating": "npm:aurelia-templating@1.0.0-beta.1.1.1"
    },
    "npm:aurelia-templating@1.0.0-beta.1.1.1": {
      "aurelia-binding": "npm:aurelia-binding@1.0.0-beta.1.1.3",
      "aurelia-dependency-injection": "npm:aurelia-dependency-injection@1.0.0-beta.1.1.3",
      "aurelia-loader": "npm:aurelia-loader@1.0.0-beta.1.1.1",
      "aurelia-logging": "npm:aurelia-logging@1.0.0-beta.1.1.1",
      "aurelia-metadata": "npm:aurelia-metadata@1.0.0-beta.1.1.4",
      "aurelia-pal": "npm:aurelia-pal@1.0.0-beta.1.1.1",
      "aurelia-path": "npm:aurelia-path@1.0.0-beta.1.1.0",
      "aurelia-task-queue": "npm:aurelia-task-queue@1.0.0-beta.1.1.1",
      "core-js": "npm:core-js@2.1.1"
    },
    "npm:babel-runtime@5.8.34": {
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:bn.js@4.10.5": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0"
    },
    "npm:browserify-aes@1.0.6": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "buffer-xor": "npm:buffer-xor@1.0.3",
      "cipher-base": "npm:cipher-base@1.0.2",
      "create-hash": "npm:create-hash@1.1.2",
      "crypto": "github:jspm/nodelibs-crypto@0.1.0",
      "evp_bytestokey": "npm:evp_bytestokey@1.0.0",
      "fs": "github:jspm/nodelibs-fs@0.1.2",
      "inherits": "npm:inherits@2.0.1",
      "systemjs-json": "github:systemjs/plugin-json@0.1.0"
    },
    "npm:browserify-cipher@1.0.0": {
      "browserify-aes": "npm:browserify-aes@1.0.6",
      "browserify-des": "npm:browserify-des@1.0.0",
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "crypto": "github:jspm/nodelibs-crypto@0.1.0",
      "evp_bytestokey": "npm:evp_bytestokey@1.0.0"
    },
    "npm:browserify-des@1.0.0": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "cipher-base": "npm:cipher-base@1.0.2",
      "crypto": "github:jspm/nodelibs-crypto@0.1.0",
      "des.js": "npm:des.js@1.0.0",
      "inherits": "npm:inherits@2.0.1"
    },
    "npm:browserify-rsa@4.0.1": {
      "bn.js": "npm:bn.js@4.10.5",
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "constants": "github:jspm/nodelibs-constants@0.1.0",
      "crypto": "github:jspm/nodelibs-crypto@0.1.0",
      "randombytes": "npm:randombytes@2.0.2"
    },
    "npm:browserify-sign@4.0.0": {
      "bn.js": "npm:bn.js@4.10.5",
      "browserify-rsa": "npm:browserify-rsa@4.0.1",
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "create-hash": "npm:create-hash@1.1.2",
      "create-hmac": "npm:create-hmac@1.1.4",
      "crypto": "github:jspm/nodelibs-crypto@0.1.0",
      "elliptic": "npm:elliptic@6.2.3",
      "inherits": "npm:inherits@2.0.1",
      "parse-asn1": "npm:parse-asn1@5.0.0",
      "stream": "github:jspm/nodelibs-stream@0.1.0"
    },
    "npm:buffer-xor@1.0.3": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "systemjs-json": "github:systemjs/plugin-json@0.1.0"
    },
    "npm:buffer@3.6.0": {
      "base64-js": "npm:base64-js@0.0.8",
      "child_process": "github:jspm/nodelibs-child_process@0.1.0",
      "fs": "github:jspm/nodelibs-fs@0.1.2",
      "ieee754": "npm:ieee754@1.1.6",
      "isarray": "npm:isarray@1.0.0",
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:cipher-base@1.0.2": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "inherits": "npm:inherits@2.0.1",
      "stream": "github:jspm/nodelibs-stream@0.1.0",
      "string_decoder": "github:jspm/nodelibs-string_decoder@0.1.0"
    },
    "npm:constants-browserify@0.0.1": {
      "systemjs-json": "github:systemjs/plugin-json@0.1.0"
    },
    "npm:core-js@1.2.6": {
      "fs": "github:jspm/nodelibs-fs@0.1.2",
      "path": "github:jspm/nodelibs-path@0.1.0",
      "process": "github:jspm/nodelibs-process@0.1.2",
      "systemjs-json": "github:systemjs/plugin-json@0.1.0"
    },
    "npm:core-js@2.1.1": {
      "fs": "github:jspm/nodelibs-fs@0.1.2",
      "path": "github:jspm/nodelibs-path@0.1.0",
      "process": "github:jspm/nodelibs-process@0.1.2",
      "systemjs-json": "github:systemjs/plugin-json@0.1.0"
    },
    "npm:core-util-is@1.0.2": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0"
    },
    "npm:create-ecdh@4.0.0": {
      "bn.js": "npm:bn.js@4.10.5",
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "crypto": "github:jspm/nodelibs-crypto@0.1.0",
      "elliptic": "npm:elliptic@6.2.3"
    },
    "npm:create-hash@1.1.2": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "cipher-base": "npm:cipher-base@1.0.2",
      "crypto": "github:jspm/nodelibs-crypto@0.1.0",
      "fs": "github:jspm/nodelibs-fs@0.1.2",
      "inherits": "npm:inherits@2.0.1",
      "ripemd160": "npm:ripemd160@1.0.1",
      "sha.js": "npm:sha.js@2.4.5"
    },
    "npm:create-hmac@1.1.4": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "create-hash": "npm:create-hash@1.1.2",
      "crypto": "github:jspm/nodelibs-crypto@0.1.0",
      "inherits": "npm:inherits@2.0.1",
      "stream": "github:jspm/nodelibs-stream@0.1.0"
    },
    "npm:crypto-browserify@3.11.0": {
      "browserify-cipher": "npm:browserify-cipher@1.0.0",
      "browserify-sign": "npm:browserify-sign@4.0.0",
      "create-ecdh": "npm:create-ecdh@4.0.0",
      "create-hash": "npm:create-hash@1.1.2",
      "create-hmac": "npm:create-hmac@1.1.4",
      "diffie-hellman": "npm:diffie-hellman@5.0.2",
      "inherits": "npm:inherits@2.0.1",
      "pbkdf2": "npm:pbkdf2@3.0.4",
      "public-encrypt": "npm:public-encrypt@4.0.0",
      "randombytes": "npm:randombytes@2.0.2"
    },
    "npm:des.js@1.0.0": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "inherits": "npm:inherits@2.0.1",
      "minimalistic-assert": "npm:minimalistic-assert@1.0.0"
    },
    "npm:diffie-hellman@5.0.2": {
      "bn.js": "npm:bn.js@4.10.5",
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "crypto": "github:jspm/nodelibs-crypto@0.1.0",
      "miller-rabin": "npm:miller-rabin@4.0.0",
      "randombytes": "npm:randombytes@2.0.2",
      "systemjs-json": "github:systemjs/plugin-json@0.1.0"
    },
    "npm:elliptic@6.2.3": {
      "bn.js": "npm:bn.js@4.10.5",
      "brorand": "npm:brorand@1.0.5",
      "hash.js": "npm:hash.js@1.0.3",
      "inherits": "npm:inherits@2.0.1",
      "systemjs-json": "github:systemjs/plugin-json@0.1.0"
    },
    "npm:evp_bytestokey@1.0.0": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "create-hash": "npm:create-hash@1.1.2",
      "crypto": "github:jspm/nodelibs-crypto@0.1.0"
    },
    "npm:font-awesome@4.5.0": {
      "css": "github:systemjs/plugin-css@0.1.20"
    },
    "npm:hash.js@1.0.3": {
      "inherits": "npm:inherits@2.0.1"
    },
    "npm:inherits@2.0.1": {
      "util": "github:jspm/nodelibs-util@0.1.0"
    },
    "npm:miller-rabin@4.0.0": {
      "bn.js": "npm:bn.js@4.10.5",
      "brorand": "npm:brorand@1.0.5"
    },
    "npm:parse-asn1@5.0.0": {
      "asn1.js": "npm:asn1.js@4.5.1",
      "browserify-aes": "npm:browserify-aes@1.0.6",
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "create-hash": "npm:create-hash@1.1.2",
      "evp_bytestokey": "npm:evp_bytestokey@1.0.0",
      "pbkdf2": "npm:pbkdf2@3.0.4",
      "systemjs-json": "github:systemjs/plugin-json@0.1.0"
    },
    "npm:path-browserify@0.0.0": {
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:pbkdf2@3.0.4": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "child_process": "github:jspm/nodelibs-child_process@0.1.0",
      "create-hmac": "npm:create-hmac@1.1.4",
      "crypto": "github:jspm/nodelibs-crypto@0.1.0",
      "path": "github:jspm/nodelibs-path@0.1.0",
      "process": "github:jspm/nodelibs-process@0.1.2",
      "systemjs-json": "github:systemjs/plugin-json@0.1.0"
    },
    "npm:process@0.11.2": {
      "assert": "github:jspm/nodelibs-assert@0.1.0"
    },
    "npm:public-encrypt@4.0.0": {
      "bn.js": "npm:bn.js@4.10.5",
      "browserify-rsa": "npm:browserify-rsa@4.0.1",
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "create-hash": "npm:create-hash@1.1.2",
      "crypto": "github:jspm/nodelibs-crypto@0.1.0",
      "parse-asn1": "npm:parse-asn1@5.0.0",
      "randombytes": "npm:randombytes@2.0.2"
    },
    "npm:randombytes@2.0.2": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "crypto": "github:jspm/nodelibs-crypto@0.1.0",
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:readable-stream@1.1.13": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "core-util-is": "npm:core-util-is@1.0.2",
      "events": "github:jspm/nodelibs-events@0.1.1",
      "inherits": "npm:inherits@2.0.1",
      "isarray": "npm:isarray@0.0.1",
      "process": "github:jspm/nodelibs-process@0.1.2",
      "stream-browserify": "npm:stream-browserify@1.0.0",
      "string_decoder": "npm:string_decoder@0.10.31"
    },
    "npm:ripemd160@1.0.1": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:sha.js@2.4.5": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "fs": "github:jspm/nodelibs-fs@0.1.2",
      "inherits": "npm:inherits@2.0.1",
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:stream-browserify@1.0.0": {
      "events": "github:jspm/nodelibs-events@0.1.1",
      "inherits": "npm:inherits@2.0.1",
      "readable-stream": "npm:readable-stream@1.1.13"
    },
    "npm:string_decoder@0.10.31": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0"
    },
    "npm:util@0.10.3": {
      "inherits": "npm:inherits@2.0.1",
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:vm-browserify@0.0.4": {
      "indexof": "npm:indexof@0.0.1"
    }
  },
  bundles: {
    "app-build-3672abd4ed": [
      "about",
      "about.html!github:systemjs/plugin-text@0.0.3",
      "app",
      "app.html!github:systemjs/plugin-text@0.0.3",
      "contact",
      "contact.html!github:systemjs/plugin-text@0.0.3",
      "diploma",
      "diploma.html!github:systemjs/plugin-text@0.0.3",
      "donate",
      "donate.html!github:systemjs/plugin-text@0.0.3",
      "faq",
      "faq.html!github:systemjs/plugin-text@0.0.3",
      "footer-elem.html!github:systemjs/plugin-text@0.0.3",
      "header-elem.html!github:systemjs/plugin-text@0.0.3",
      "index",
      "index.html!github:systemjs/plugin-text@0.0.3",
      "main",
      "partners",
      "partners.html!github:systemjs/plugin-text@0.0.3",
      "support-router",
      "support-router.html!github:systemjs/plugin-text@0.0.3",
      "terms-router",
      "terms-router.html!github:systemjs/plugin-text@0.0.3"
    ],
    "aurelia-2a69a17975": [
      "github:components/jquery@2.2.0",
      "github:components/jquery@2.2.0/jquery",
      "github:guillaumepotier/Parsley.js@2.3.4",
      "github:guillaumepotier/Parsley.js@2.3.4/dist/parsley",
      "github:itmcdev/aurelia-google-recaptcha@master",
      "github:itmcdev/aurelia-google-recaptcha@master/index",
      "github:jspm/nodelibs-process@0.1.2",
      "github:jspm/nodelibs-process@0.1.2/index",
      "github:twbs/bootstrap@3.3.6",
      "github:twbs/bootstrap@3.3.6/css/bootstrap.css!github:systemjs/plugin-text@0.0.3",
      "github:twbs/bootstrap@3.3.6/js/bootstrap",
      "npm:aurelia-animator-css@1.0.0-beta.1.0.3",
      "npm:aurelia-animator-css@1.0.0-beta.1.0.3/aurelia-animator-css",
      "npm:aurelia-binding@1.0.0-beta.1.1.3",
      "npm:aurelia-binding@1.0.0-beta.1.1.3/aurelia-binding",
      "npm:aurelia-bootstrapper@1.0.0-beta.1.0.2",
      "npm:aurelia-bootstrapper@1.0.0-beta.1.0.2/aurelia-bootstrapper",
      "npm:aurelia-dependency-injection@1.0.0-beta.1.1.3",
      "npm:aurelia-dependency-injection@1.0.0-beta.1.1.3/aurelia-dependency-injection",
      "npm:aurelia-event-aggregator@1.0.0-beta.1",
      "npm:aurelia-event-aggregator@1.0.0-beta.1/aurelia-event-aggregator",
      "npm:aurelia-fetch-client@1.0.0-beta.1.0.2",
      "npm:aurelia-fetch-client@1.0.0-beta.1.0.2/aurelia-fetch-client",
      "npm:aurelia-framework@1.0.0-beta.1.1.3",
      "npm:aurelia-framework@1.0.0-beta.1.1.3/aurelia-framework",
      "npm:aurelia-history-browser@1.0.0-beta.1.0.1",
      "npm:aurelia-history-browser@1.0.0-beta.1.0.1/aurelia-history-browser",
      "npm:aurelia-history@1.0.0-beta.1",
      "npm:aurelia-history@1.0.0-beta.1/aurelia-history",
      "npm:aurelia-loader-default@1.0.0-beta.1.0.2",
      "npm:aurelia-loader-default@1.0.0-beta.1.0.2/aurelia-loader-default",
      "npm:aurelia-loader@1.0.0-beta.1.1.1",
      "npm:aurelia-loader@1.0.0-beta.1.1.1/aurelia-loader",
      "npm:aurelia-logging-console@1.0.0-beta.1",
      "npm:aurelia-logging-console@1.0.0-beta.1/aurelia-logging-console",
      "npm:aurelia-logging@1.0.0-beta.1.1.1",
      "npm:aurelia-logging@1.0.0-beta.1.1.1/aurelia-logging",
      "npm:aurelia-metadata@1.0.0-beta.1.1.4",
      "npm:aurelia-metadata@1.0.0-beta.1.1.4/aurelia-metadata",
      "npm:aurelia-pal-browser@1.0.0-beta.1.0.3",
      "npm:aurelia-pal-browser@1.0.0-beta.1.0.3/aurelia-pal-browser",
      "npm:aurelia-pal@1.0.0-beta.1.1.1",
      "npm:aurelia-pal@1.0.0-beta.1.1.1/aurelia-pal",
      "npm:aurelia-path@1.0.0-beta.1.1.0",
      "npm:aurelia-path@1.0.0-beta.1.1.0/aurelia-path",
      "npm:aurelia-route-recognizer@1.0.0-beta.1",
      "npm:aurelia-route-recognizer@1.0.0-beta.1/aurelia-route-recognizer",
      "npm:aurelia-router@1.0.0-beta.1.0.1",
      "npm:aurelia-router@1.0.0-beta.1.0.1/aurelia-router",
      "npm:aurelia-task-queue@1.0.0-beta.1.1.1",
      "npm:aurelia-task-queue@1.0.0-beta.1.1.1/aurelia-task-queue",
      "npm:aurelia-templating-binding@1.0.0-beta.1.0.2",
      "npm:aurelia-templating-binding@1.0.0-beta.1.0.2/aurelia-templating-binding",
      "npm:aurelia-templating-resources@1.0.0-beta.1.0.4",
      "npm:aurelia-templating-resources@1.0.0-beta.1.0.4/analyze-view-factory",
      "npm:aurelia-templating-resources@1.0.0-beta.1.0.4/array-repeat-strategy",
      "npm:aurelia-templating-resources@1.0.0-beta.1.0.4/aurelia-templating-resources",
      "npm:aurelia-templating-resources@1.0.0-beta.1.0.4/binding-mode-behaviors",
      "npm:aurelia-templating-resources@1.0.0-beta.1.0.4/binding-signaler",
      "npm:aurelia-templating-resources@1.0.0-beta.1.0.4/compile-spy",
      "npm:aurelia-templating-resources@1.0.0-beta.1.0.4/compose",
      "npm:aurelia-templating-resources@1.0.0-beta.1.0.4/css-resource",
      "npm:aurelia-templating-resources@1.0.0-beta.1.0.4/debounce-binding-behavior",
      "npm:aurelia-templating-resources@1.0.0-beta.1.0.4/dynamic-element",
      "npm:aurelia-templating-resources@1.0.0-beta.1.0.4/focus",
      "npm:aurelia-templating-resources@1.0.0-beta.1.0.4/html-sanitizer",
      "npm:aurelia-templating-resources@1.0.0-beta.1.0.4/if",
      "npm:aurelia-templating-resources@1.0.0-beta.1.0.4/map-repeat-strategy",
      "npm:aurelia-templating-resources@1.0.0-beta.1.0.4/null-repeat-strategy",
      "npm:aurelia-templating-resources@1.0.0-beta.1.0.4/number-repeat-strategy",
      "npm:aurelia-templating-resources@1.0.0-beta.1.0.4/repeat",
      "npm:aurelia-templating-resources@1.0.0-beta.1.0.4/repeat-strategy-locator",
      "npm:aurelia-templating-resources@1.0.0-beta.1.0.4/repeat-utilities",
      "npm:aurelia-templating-resources@1.0.0-beta.1.0.4/replaceable",
      "npm:aurelia-templating-resources@1.0.0-beta.1.0.4/sanitize-html",
      "npm:aurelia-templating-resources@1.0.0-beta.1.0.4/set-repeat-strategy",
      "npm:aurelia-templating-resources@1.0.0-beta.1.0.4/show",
      "npm:aurelia-templating-resources@1.0.0-beta.1.0.4/signal-binding-behavior",
      "npm:aurelia-templating-resources@1.0.0-beta.1.0.4/throttle-binding-behavior",
      "npm:aurelia-templating-resources@1.0.0-beta.1.0.4/update-trigger-binding-behavior",
      "npm:aurelia-templating-resources@1.0.0-beta.1.0.4/view-spy",
      "npm:aurelia-templating-resources@1.0.0-beta.1.0.4/with",
      "npm:aurelia-templating-router@1.0.0-beta.1.0.5",
      "npm:aurelia-templating-router@1.0.0-beta.1.0.5/aurelia-templating-router",
      "npm:aurelia-templating-router@1.0.0-beta.1.0.5/route-href",
      "npm:aurelia-templating-router@1.0.0-beta.1.0.5/route-loader",
      "npm:aurelia-templating-router@1.0.0-beta.1.0.5/router-view",
      "npm:aurelia-templating@1.0.0-beta.1.1.1",
      "npm:aurelia-templating@1.0.0-beta.1.1.1/aurelia-templating",
      "npm:core-js@1.2.6",
      "npm:core-js@1.2.6/index",
      "npm:core-js@1.2.6/modules/$",
      "npm:core-js@1.2.6/modules/$.a-function",
      "npm:core-js@1.2.6/modules/$.add-to-unscopables",
      "npm:core-js@1.2.6/modules/$.an-object",
      "npm:core-js@1.2.6/modules/$.array-copy-within",
      "npm:core-js@1.2.6/modules/$.array-fill",
      "npm:core-js@1.2.6/modules/$.array-includes",
      "npm:core-js@1.2.6/modules/$.array-methods",
      "npm:core-js@1.2.6/modules/$.array-species-create",
      "npm:core-js@1.2.6/modules/$.classof",
      "npm:core-js@1.2.6/modules/$.cof",
      "npm:core-js@1.2.6/modules/$.collection",
      "npm:core-js@1.2.6/modules/$.collection-strong",
      "npm:core-js@1.2.6/modules/$.collection-to-json",
      "npm:core-js@1.2.6/modules/$.collection-weak",
      "npm:core-js@1.2.6/modules/$.core",
      "npm:core-js@1.2.6/modules/$.ctx",
      "npm:core-js@1.2.6/modules/$.defined",
      "npm:core-js@1.2.6/modules/$.descriptors",
      "npm:core-js@1.2.6/modules/$.dom-create",
      "npm:core-js@1.2.6/modules/$.enum-keys",
      "npm:core-js@1.2.6/modules/$.export",
      "npm:core-js@1.2.6/modules/$.fails",
      "npm:core-js@1.2.6/modules/$.fails-is-regexp",
      "npm:core-js@1.2.6/modules/$.fix-re-wks",
      "npm:core-js@1.2.6/modules/$.flags",
      "npm:core-js@1.2.6/modules/$.for-of",
      "npm:core-js@1.2.6/modules/$.get-names",
      "npm:core-js@1.2.6/modules/$.global",
      "npm:core-js@1.2.6/modules/$.has",
      "npm:core-js@1.2.6/modules/$.hide",
      "npm:core-js@1.2.6/modules/$.html",
      "npm:core-js@1.2.6/modules/$.invoke",
      "npm:core-js@1.2.6/modules/$.iobject",
      "npm:core-js@1.2.6/modules/$.is-array",
      "npm:core-js@1.2.6/modules/$.is-array-iter",
      "npm:core-js@1.2.6/modules/$.is-integer",
      "npm:core-js@1.2.6/modules/$.is-object",
      "npm:core-js@1.2.6/modules/$.is-regexp",
      "npm:core-js@1.2.6/modules/$.iter-call",
      "npm:core-js@1.2.6/modules/$.iter-create",
      "npm:core-js@1.2.6/modules/$.iter-define",
      "npm:core-js@1.2.6/modules/$.iter-detect",
      "npm:core-js@1.2.6/modules/$.iter-step",
      "npm:core-js@1.2.6/modules/$.iterators",
      "npm:core-js@1.2.6/modules/$.keyof",
      "npm:core-js@1.2.6/modules/$.library",
      "npm:core-js@1.2.6/modules/$.math-expm1",
      "npm:core-js@1.2.6/modules/$.math-log1p",
      "npm:core-js@1.2.6/modules/$.math-sign",
      "npm:core-js@1.2.6/modules/$.microtask",
      "npm:core-js@1.2.6/modules/$.object-assign",
      "npm:core-js@1.2.6/modules/$.object-define",
      "npm:core-js@1.2.6/modules/$.object-sap",
      "npm:core-js@1.2.6/modules/$.object-to-array",
      "npm:core-js@1.2.6/modules/$.own-keys",
      "npm:core-js@1.2.6/modules/$.partial",
      "npm:core-js@1.2.6/modules/$.path",
      "npm:core-js@1.2.6/modules/$.property-desc",
      "npm:core-js@1.2.6/modules/$.redefine",
      "npm:core-js@1.2.6/modules/$.redefine-all",
      "npm:core-js@1.2.6/modules/$.replacer",
      "npm:core-js@1.2.6/modules/$.same-value",
      "npm:core-js@1.2.6/modules/$.set-proto",
      "npm:core-js@1.2.6/modules/$.set-species",
      "npm:core-js@1.2.6/modules/$.set-to-string-tag",
      "npm:core-js@1.2.6/modules/$.shared",
      "npm:core-js@1.2.6/modules/$.species-constructor",
      "npm:core-js@1.2.6/modules/$.strict-new",
      "npm:core-js@1.2.6/modules/$.string-at",
      "npm:core-js@1.2.6/modules/$.string-context",
      "npm:core-js@1.2.6/modules/$.string-pad",
      "npm:core-js@1.2.6/modules/$.string-repeat",
      "npm:core-js@1.2.6/modules/$.string-trim",
      "npm:core-js@1.2.6/modules/$.task",
      "npm:core-js@1.2.6/modules/$.to-index",
      "npm:core-js@1.2.6/modules/$.to-integer",
      "npm:core-js@1.2.6/modules/$.to-iobject",
      "npm:core-js@1.2.6/modules/$.to-length",
      "npm:core-js@1.2.6/modules/$.to-object",
      "npm:core-js@1.2.6/modules/$.to-primitive",
      "npm:core-js@1.2.6/modules/$.uid",
      "npm:core-js@1.2.6/modules/$.wks",
      "npm:core-js@1.2.6/modules/core.delay",
      "npm:core-js@1.2.6/modules/core.dict",
      "npm:core-js@1.2.6/modules/core.function.part",
      "npm:core-js@1.2.6/modules/core.get-iterator",
      "npm:core-js@1.2.6/modules/core.get-iterator-method",
      "npm:core-js@1.2.6/modules/core.is-iterable",
      "npm:core-js@1.2.6/modules/core.log",
      "npm:core-js@1.2.6/modules/core.number.iterator",
      "npm:core-js@1.2.6/modules/core.object.classof",
      "npm:core-js@1.2.6/modules/core.object.define",
      "npm:core-js@1.2.6/modules/core.object.is-object",
      "npm:core-js@1.2.6/modules/core.object.make",
      "npm:core-js@1.2.6/modules/core.string.escape-html",
      "npm:core-js@1.2.6/modules/core.string.unescape-html",
      "npm:core-js@1.2.6/modules/es5",
      "npm:core-js@1.2.6/modules/es6.array.copy-within",
      "npm:core-js@1.2.6/modules/es6.array.fill",
      "npm:core-js@1.2.6/modules/es6.array.find",
      "npm:core-js@1.2.6/modules/es6.array.find-index",
      "npm:core-js@1.2.6/modules/es6.array.from",
      "npm:core-js@1.2.6/modules/es6.array.iterator",
      "npm:core-js@1.2.6/modules/es6.array.of",
      "npm:core-js@1.2.6/modules/es6.array.species",
      "npm:core-js@1.2.6/modules/es6.function.has-instance",
      "npm:core-js@1.2.6/modules/es6.function.name",
      "npm:core-js@1.2.6/modules/es6.map",
      "npm:core-js@1.2.6/modules/es6.math.acosh",
      "npm:core-js@1.2.6/modules/es6.math.asinh",
      "npm:core-js@1.2.6/modules/es6.math.atanh",
      "npm:core-js@1.2.6/modules/es6.math.cbrt",
      "npm:core-js@1.2.6/modules/es6.math.clz32",
      "npm:core-js@1.2.6/modules/es6.math.cosh",
      "npm:core-js@1.2.6/modules/es6.math.expm1",
      "npm:core-js@1.2.6/modules/es6.math.fround",
      "npm:core-js@1.2.6/modules/es6.math.hypot",
      "npm:core-js@1.2.6/modules/es6.math.imul",
      "npm:core-js@1.2.6/modules/es6.math.log10",
      "npm:core-js@1.2.6/modules/es6.math.log1p",
      "npm:core-js@1.2.6/modules/es6.math.log2",
      "npm:core-js@1.2.6/modules/es6.math.sign",
      "npm:core-js@1.2.6/modules/es6.math.sinh",
      "npm:core-js@1.2.6/modules/es6.math.tanh",
      "npm:core-js@1.2.6/modules/es6.math.trunc",
      "npm:core-js@1.2.6/modules/es6.number.constructor",
      "npm:core-js@1.2.6/modules/es6.number.epsilon",
      "npm:core-js@1.2.6/modules/es6.number.is-finite",
      "npm:core-js@1.2.6/modules/es6.number.is-integer",
      "npm:core-js@1.2.6/modules/es6.number.is-nan",
      "npm:core-js@1.2.6/modules/es6.number.is-safe-integer",
      "npm:core-js@1.2.6/modules/es6.number.max-safe-integer",
      "npm:core-js@1.2.6/modules/es6.number.min-safe-integer",
      "npm:core-js@1.2.6/modules/es6.number.parse-float",
      "npm:core-js@1.2.6/modules/es6.number.parse-int",
      "npm:core-js@1.2.6/modules/es6.object.assign",
      "npm:core-js@1.2.6/modules/es6.object.freeze",
      "npm:core-js@1.2.6/modules/es6.object.get-own-property-descriptor",
      "npm:core-js@1.2.6/modules/es6.object.get-own-property-names",
      "npm:core-js@1.2.6/modules/es6.object.get-prototype-of",
      "npm:core-js@1.2.6/modules/es6.object.is",
      "npm:core-js@1.2.6/modules/es6.object.is-extensible",
      "npm:core-js@1.2.6/modules/es6.object.is-frozen",
      "npm:core-js@1.2.6/modules/es6.object.is-sealed",
      "npm:core-js@1.2.6/modules/es6.object.keys",
      "npm:core-js@1.2.6/modules/es6.object.prevent-extensions",
      "npm:core-js@1.2.6/modules/es6.object.seal",
      "npm:core-js@1.2.6/modules/es6.object.set-prototype-of",
      "npm:core-js@1.2.6/modules/es6.object.to-string",
      "npm:core-js@1.2.6/modules/es6.promise",
      "npm:core-js@1.2.6/modules/es6.reflect.apply",
      "npm:core-js@1.2.6/modules/es6.reflect.construct",
      "npm:core-js@1.2.6/modules/es6.reflect.define-property",
      "npm:core-js@1.2.6/modules/es6.reflect.delete-property",
      "npm:core-js@1.2.6/modules/es6.reflect.enumerate",
      "npm:core-js@1.2.6/modules/es6.reflect.get",
      "npm:core-js@1.2.6/modules/es6.reflect.get-own-property-descriptor",
      "npm:core-js@1.2.6/modules/es6.reflect.get-prototype-of",
      "npm:core-js@1.2.6/modules/es6.reflect.has",
      "npm:core-js@1.2.6/modules/es6.reflect.is-extensible",
      "npm:core-js@1.2.6/modules/es6.reflect.own-keys",
      "npm:core-js@1.2.6/modules/es6.reflect.prevent-extensions",
      "npm:core-js@1.2.6/modules/es6.reflect.set",
      "npm:core-js@1.2.6/modules/es6.reflect.set-prototype-of",
      "npm:core-js@1.2.6/modules/es6.regexp.constructor",
      "npm:core-js@1.2.6/modules/es6.regexp.flags",
      "npm:core-js@1.2.6/modules/es6.regexp.match",
      "npm:core-js@1.2.6/modules/es6.regexp.replace",
      "npm:core-js@1.2.6/modules/es6.regexp.search",
      "npm:core-js@1.2.6/modules/es6.regexp.split",
      "npm:core-js@1.2.6/modules/es6.set",
      "npm:core-js@1.2.6/modules/es6.string.code-point-at",
      "npm:core-js@1.2.6/modules/es6.string.ends-with",
      "npm:core-js@1.2.6/modules/es6.string.from-code-point",
      "npm:core-js@1.2.6/modules/es6.string.includes",
      "npm:core-js@1.2.6/modules/es6.string.iterator",
      "npm:core-js@1.2.6/modules/es6.string.raw",
      "npm:core-js@1.2.6/modules/es6.string.repeat",
      "npm:core-js@1.2.6/modules/es6.string.starts-with",
      "npm:core-js@1.2.6/modules/es6.string.trim",
      "npm:core-js@1.2.6/modules/es6.symbol",
      "npm:core-js@1.2.6/modules/es6.weak-map",
      "npm:core-js@1.2.6/modules/es6.weak-set",
      "npm:core-js@1.2.6/modules/es7.array.includes",
      "npm:core-js@1.2.6/modules/es7.map.to-json",
      "npm:core-js@1.2.6/modules/es7.object.entries",
      "npm:core-js@1.2.6/modules/es7.object.get-own-property-descriptors",
      "npm:core-js@1.2.6/modules/es7.object.values",
      "npm:core-js@1.2.6/modules/es7.regexp.escape",
      "npm:core-js@1.2.6/modules/es7.set.to-json",
      "npm:core-js@1.2.6/modules/es7.string.at",
      "npm:core-js@1.2.6/modules/es7.string.pad-left",
      "npm:core-js@1.2.6/modules/es7.string.pad-right",
      "npm:core-js@1.2.6/modules/es7.string.trim-left",
      "npm:core-js@1.2.6/modules/es7.string.trim-right",
      "npm:core-js@1.2.6/modules/js.array.statics",
      "npm:core-js@1.2.6/modules/web.dom.iterable",
      "npm:core-js@1.2.6/modules/web.immediate",
      "npm:core-js@1.2.6/modules/web.timers",
      "npm:core-js@1.2.6/shim",
      "npm:core-js@2.1.1",
      "npm:core-js@2.1.1/index",
      "npm:core-js@2.1.1/modules/_a-function",
      "npm:core-js@2.1.1/modules/_a-number-value",
      "npm:core-js@2.1.1/modules/_add-to-unscopables",
      "npm:core-js@2.1.1/modules/_an-instance",
      "npm:core-js@2.1.1/modules/_an-object",
      "npm:core-js@2.1.1/modules/_array-copy-within",
      "npm:core-js@2.1.1/modules/_array-fill",
      "npm:core-js@2.1.1/modules/_array-from-iterable",
      "npm:core-js@2.1.1/modules/_array-includes",
      "npm:core-js@2.1.1/modules/_array-methods",
      "npm:core-js@2.1.1/modules/_array-reduce",
      "npm:core-js@2.1.1/modules/_array-species-create",
      "npm:core-js@2.1.1/modules/_bind",
      "npm:core-js@2.1.1/modules/_classof",
      "npm:core-js@2.1.1/modules/_cof",
      "npm:core-js@2.1.1/modules/_collection",
      "npm:core-js@2.1.1/modules/_collection-strong",
      "npm:core-js@2.1.1/modules/_collection-to-json",
      "npm:core-js@2.1.1/modules/_collection-weak",
      "npm:core-js@2.1.1/modules/_core",
      "npm:core-js@2.1.1/modules/_ctx",
      "npm:core-js@2.1.1/modules/_defined",
      "npm:core-js@2.1.1/modules/_descriptors",
      "npm:core-js@2.1.1/modules/_dom-create",
      "npm:core-js@2.1.1/modules/_enum-bug-keys",
      "npm:core-js@2.1.1/modules/_enum-keys",
      "npm:core-js@2.1.1/modules/_export",
      "npm:core-js@2.1.1/modules/_fails",
      "npm:core-js@2.1.1/modules/_fails-is-regexp",
      "npm:core-js@2.1.1/modules/_fix-re-wks",
      "npm:core-js@2.1.1/modules/_flags",
      "npm:core-js@2.1.1/modules/_for-of",
      "npm:core-js@2.1.1/modules/_global",
      "npm:core-js@2.1.1/modules/_has",
      "npm:core-js@2.1.1/modules/_hide",
      "npm:core-js@2.1.1/modules/_html",
      "npm:core-js@2.1.1/modules/_ie8-dom-define",
      "npm:core-js@2.1.1/modules/_inherit-if-required",
      "npm:core-js@2.1.1/modules/_invoke",
      "npm:core-js@2.1.1/modules/_iobject",
      "npm:core-js@2.1.1/modules/_is-array",
      "npm:core-js@2.1.1/modules/_is-array-iter",
      "npm:core-js@2.1.1/modules/_is-integer",
      "npm:core-js@2.1.1/modules/_is-object",
      "npm:core-js@2.1.1/modules/_is-regexp",
      "npm:core-js@2.1.1/modules/_iter-call",
      "npm:core-js@2.1.1/modules/_iter-create",
      "npm:core-js@2.1.1/modules/_iter-define",
      "npm:core-js@2.1.1/modules/_iter-detect",
      "npm:core-js@2.1.1/modules/_iter-step",
      "npm:core-js@2.1.1/modules/_iterators",
      "npm:core-js@2.1.1/modules/_keyof",
      "npm:core-js@2.1.1/modules/_library",
      "npm:core-js@2.1.1/modules/_math-expm1",
      "npm:core-js@2.1.1/modules/_math-log1p",
      "npm:core-js@2.1.1/modules/_math-sign",
      "npm:core-js@2.1.1/modules/_meta",
      "npm:core-js@2.1.1/modules/_metadata",
      "npm:core-js@2.1.1/modules/_microtask",
      "npm:core-js@2.1.1/modules/_object-assign",
      "npm:core-js@2.1.1/modules/_object-create",
      "npm:core-js@2.1.1/modules/_object-define",
      "npm:core-js@2.1.1/modules/_object-dp",
      "npm:core-js@2.1.1/modules/_object-dps",
      "npm:core-js@2.1.1/modules/_object-gopd",
      "npm:core-js@2.1.1/modules/_object-gopn",
      "npm:core-js@2.1.1/modules/_object-gopn-ext",
      "npm:core-js@2.1.1/modules/_object-gops",
      "npm:core-js@2.1.1/modules/_object-gpo",
      "npm:core-js@2.1.1/modules/_object-keys",
      "npm:core-js@2.1.1/modules/_object-keys-internal",
      "npm:core-js@2.1.1/modules/_object-pie",
      "npm:core-js@2.1.1/modules/_object-sap",
      "npm:core-js@2.1.1/modules/_object-to-array",
      "npm:core-js@2.1.1/modules/_own-keys",
      "npm:core-js@2.1.1/modules/_parse-float",
      "npm:core-js@2.1.1/modules/_parse-int",
      "npm:core-js@2.1.1/modules/_partial",
      "npm:core-js@2.1.1/modules/_path",
      "npm:core-js@2.1.1/modules/_property-desc",
      "npm:core-js@2.1.1/modules/_redefine",
      "npm:core-js@2.1.1/modules/_redefine-all",
      "npm:core-js@2.1.1/modules/_replacer",
      "npm:core-js@2.1.1/modules/_same-value",
      "npm:core-js@2.1.1/modules/_set-proto",
      "npm:core-js@2.1.1/modules/_set-species",
      "npm:core-js@2.1.1/modules/_set-to-string-tag",
      "npm:core-js@2.1.1/modules/_shared",
      "npm:core-js@2.1.1/modules/_shared-key",
      "npm:core-js@2.1.1/modules/_species-constructor",
      "npm:core-js@2.1.1/modules/_strict-method",
      "npm:core-js@2.1.1/modules/_string-at",
      "npm:core-js@2.1.1/modules/_string-context",
      "npm:core-js@2.1.1/modules/_string-html",
      "npm:core-js@2.1.1/modules/_string-pad",
      "npm:core-js@2.1.1/modules/_string-repeat",
      "npm:core-js@2.1.1/modules/_string-trim",
      "npm:core-js@2.1.1/modules/_string-ws",
      "npm:core-js@2.1.1/modules/_task",
      "npm:core-js@2.1.1/modules/_to-index",
      "npm:core-js@2.1.1/modules/_to-integer",
      "npm:core-js@2.1.1/modules/_to-iobject",
      "npm:core-js@2.1.1/modules/_to-length",
      "npm:core-js@2.1.1/modules/_to-object",
      "npm:core-js@2.1.1/modules/_to-primitive",
      "npm:core-js@2.1.1/modules/_typed",
      "npm:core-js@2.1.1/modules/_typed-array",
      "npm:core-js@2.1.1/modules/_typed-buffer",
      "npm:core-js@2.1.1/modules/_uid",
      "npm:core-js@2.1.1/modules/_wks",
      "npm:core-js@2.1.1/modules/core.delay",
      "npm:core-js@2.1.1/modules/core.dict",
      "npm:core-js@2.1.1/modules/core.function.part",
      "npm:core-js@2.1.1/modules/core.get-iterator",
      "npm:core-js@2.1.1/modules/core.get-iterator-method",
      "npm:core-js@2.1.1/modules/core.is-iterable",
      "npm:core-js@2.1.1/modules/core.number.iterator",
      "npm:core-js@2.1.1/modules/core.object.classof",
      "npm:core-js@2.1.1/modules/core.object.define",
      "npm:core-js@2.1.1/modules/core.object.is-object",
      "npm:core-js@2.1.1/modules/core.object.make",
      "npm:core-js@2.1.1/modules/core.regexp.escape",
      "npm:core-js@2.1.1/modules/core.string.escape-html",
      "npm:core-js@2.1.1/modules/core.string.unescape-html",
      "npm:core-js@2.1.1/modules/es6.array.copy-within",
      "npm:core-js@2.1.1/modules/es6.array.every",
      "npm:core-js@2.1.1/modules/es6.array.fill",
      "npm:core-js@2.1.1/modules/es6.array.filter",
      "npm:core-js@2.1.1/modules/es6.array.find",
      "npm:core-js@2.1.1/modules/es6.array.find-index",
      "npm:core-js@2.1.1/modules/es6.array.for-each",
      "npm:core-js@2.1.1/modules/es6.array.from",
      "npm:core-js@2.1.1/modules/es6.array.index-of",
      "npm:core-js@2.1.1/modules/es6.array.is-array",
      "npm:core-js@2.1.1/modules/es6.array.iterator",
      "npm:core-js@2.1.1/modules/es6.array.join",
      "npm:core-js@2.1.1/modules/es6.array.last-index-of",
      "npm:core-js@2.1.1/modules/es6.array.map",
      "npm:core-js@2.1.1/modules/es6.array.of",
      "npm:core-js@2.1.1/modules/es6.array.reduce",
      "npm:core-js@2.1.1/modules/es6.array.reduce-right",
      "npm:core-js@2.1.1/modules/es6.array.slice",
      "npm:core-js@2.1.1/modules/es6.array.some",
      "npm:core-js@2.1.1/modules/es6.array.sort",
      "npm:core-js@2.1.1/modules/es6.array.species",
      "npm:core-js@2.1.1/modules/es6.date.now",
      "npm:core-js@2.1.1/modules/es6.date.to-iso-string",
      "npm:core-js@2.1.1/modules/es6.date.to-json",
      "npm:core-js@2.1.1/modules/es6.date.to-string",
      "npm:core-js@2.1.1/modules/es6.function.bind",
      "npm:core-js@2.1.1/modules/es6.function.has-instance",
      "npm:core-js@2.1.1/modules/es6.function.name",
      "npm:core-js@2.1.1/modules/es6.map",
      "npm:core-js@2.1.1/modules/es6.math.acosh",
      "npm:core-js@2.1.1/modules/es6.math.asinh",
      "npm:core-js@2.1.1/modules/es6.math.atanh",
      "npm:core-js@2.1.1/modules/es6.math.cbrt",
      "npm:core-js@2.1.1/modules/es6.math.clz32",
      "npm:core-js@2.1.1/modules/es6.math.cosh",
      "npm:core-js@2.1.1/modules/es6.math.expm1",
      "npm:core-js@2.1.1/modules/es6.math.fround",
      "npm:core-js@2.1.1/modules/es6.math.hypot",
      "npm:core-js@2.1.1/modules/es6.math.imul",
      "npm:core-js@2.1.1/modules/es6.math.log10",
      "npm:core-js@2.1.1/modules/es6.math.log1p",
      "npm:core-js@2.1.1/modules/es6.math.log2",
      "npm:core-js@2.1.1/modules/es6.math.sign",
      "npm:core-js@2.1.1/modules/es6.math.sinh",
      "npm:core-js@2.1.1/modules/es6.math.tanh",
      "npm:core-js@2.1.1/modules/es6.math.trunc",
      "npm:core-js@2.1.1/modules/es6.number.constructor",
      "npm:core-js@2.1.1/modules/es6.number.epsilon",
      "npm:core-js@2.1.1/modules/es6.number.is-finite",
      "npm:core-js@2.1.1/modules/es6.number.is-integer",
      "npm:core-js@2.1.1/modules/es6.number.is-nan",
      "npm:core-js@2.1.1/modules/es6.number.is-safe-integer",
      "npm:core-js@2.1.1/modules/es6.number.max-safe-integer",
      "npm:core-js@2.1.1/modules/es6.number.min-safe-integer",
      "npm:core-js@2.1.1/modules/es6.number.parse-float",
      "npm:core-js@2.1.1/modules/es6.number.parse-int",
      "npm:core-js@2.1.1/modules/es6.number.to-fixed",
      "npm:core-js@2.1.1/modules/es6.number.to-precision",
      "npm:core-js@2.1.1/modules/es6.object.assign",
      "npm:core-js@2.1.1/modules/es6.object.create",
      "npm:core-js@2.1.1/modules/es6.object.define-properties",
      "npm:core-js@2.1.1/modules/es6.object.define-property",
      "npm:core-js@2.1.1/modules/es6.object.freeze",
      "npm:core-js@2.1.1/modules/es6.object.get-own-property-descriptor",
      "npm:core-js@2.1.1/modules/es6.object.get-own-property-names",
      "npm:core-js@2.1.1/modules/es6.object.get-prototype-of",
      "npm:core-js@2.1.1/modules/es6.object.is",
      "npm:core-js@2.1.1/modules/es6.object.is-extensible",
      "npm:core-js@2.1.1/modules/es6.object.is-frozen",
      "npm:core-js@2.1.1/modules/es6.object.is-sealed",
      "npm:core-js@2.1.1/modules/es6.object.keys",
      "npm:core-js@2.1.1/modules/es6.object.prevent-extensions",
      "npm:core-js@2.1.1/modules/es6.object.seal",
      "npm:core-js@2.1.1/modules/es6.object.set-prototype-of",
      "npm:core-js@2.1.1/modules/es6.object.to-string",
      "npm:core-js@2.1.1/modules/es6.parse-float",
      "npm:core-js@2.1.1/modules/es6.parse-int",
      "npm:core-js@2.1.1/modules/es6.promise",
      "npm:core-js@2.1.1/modules/es6.reflect.apply",
      "npm:core-js@2.1.1/modules/es6.reflect.construct",
      "npm:core-js@2.1.1/modules/es6.reflect.define-property",
      "npm:core-js@2.1.1/modules/es6.reflect.delete-property",
      "npm:core-js@2.1.1/modules/es6.reflect.enumerate",
      "npm:core-js@2.1.1/modules/es6.reflect.get",
      "npm:core-js@2.1.1/modules/es6.reflect.get-own-property-descriptor",
      "npm:core-js@2.1.1/modules/es6.reflect.get-prototype-of",
      "npm:core-js@2.1.1/modules/es6.reflect.has",
      "npm:core-js@2.1.1/modules/es6.reflect.is-extensible",
      "npm:core-js@2.1.1/modules/es6.reflect.own-keys",
      "npm:core-js@2.1.1/modules/es6.reflect.prevent-extensions",
      "npm:core-js@2.1.1/modules/es6.reflect.set",
      "npm:core-js@2.1.1/modules/es6.reflect.set-prototype-of",
      "npm:core-js@2.1.1/modules/es6.regexp.constructor",
      "npm:core-js@2.1.1/modules/es6.regexp.flags",
      "npm:core-js@2.1.1/modules/es6.regexp.match",
      "npm:core-js@2.1.1/modules/es6.regexp.replace",
      "npm:core-js@2.1.1/modules/es6.regexp.search",
      "npm:core-js@2.1.1/modules/es6.regexp.split",
      "npm:core-js@2.1.1/modules/es6.regexp.to-string",
      "npm:core-js@2.1.1/modules/es6.set",
      "npm:core-js@2.1.1/modules/es6.string.anchor",
      "npm:core-js@2.1.1/modules/es6.string.big",
      "npm:core-js@2.1.1/modules/es6.string.blink",
      "npm:core-js@2.1.1/modules/es6.string.bold",
      "npm:core-js@2.1.1/modules/es6.string.code-point-at",
      "npm:core-js@2.1.1/modules/es6.string.ends-with",
      "npm:core-js@2.1.1/modules/es6.string.fixed",
      "npm:core-js@2.1.1/modules/es6.string.fontcolor",
      "npm:core-js@2.1.1/modules/es6.string.fontsize",
      "npm:core-js@2.1.1/modules/es6.string.from-code-point",
      "npm:core-js@2.1.1/modules/es6.string.includes",
      "npm:core-js@2.1.1/modules/es6.string.italics",
      "npm:core-js@2.1.1/modules/es6.string.iterator",
      "npm:core-js@2.1.1/modules/es6.string.link",
      "npm:core-js@2.1.1/modules/es6.string.raw",
      "npm:core-js@2.1.1/modules/es6.string.repeat",
      "npm:core-js@2.1.1/modules/es6.string.small",
      "npm:core-js@2.1.1/modules/es6.string.starts-with",
      "npm:core-js@2.1.1/modules/es6.string.strike",
      "npm:core-js@2.1.1/modules/es6.string.sub",
      "npm:core-js@2.1.1/modules/es6.string.sup",
      "npm:core-js@2.1.1/modules/es6.string.trim",
      "npm:core-js@2.1.1/modules/es6.symbol",
      "npm:core-js@2.1.1/modules/es6.typed.array-buffer",
      "npm:core-js@2.1.1/modules/es6.typed.data-view",
      "npm:core-js@2.1.1/modules/es6.typed.float32-array",
      "npm:core-js@2.1.1/modules/es6.typed.float64-array",
      "npm:core-js@2.1.1/modules/es6.typed.int16-array",
      "npm:core-js@2.1.1/modules/es6.typed.int32-array",
      "npm:core-js@2.1.1/modules/es6.typed.int8-array",
      "npm:core-js@2.1.1/modules/es6.typed.uint16-array",
      "npm:core-js@2.1.1/modules/es6.typed.uint32-array",
      "npm:core-js@2.1.1/modules/es6.typed.uint8-array",
      "npm:core-js@2.1.1/modules/es6.typed.uint8-clamped-array",
      "npm:core-js@2.1.1/modules/es6.weak-map",
      "npm:core-js@2.1.1/modules/es6.weak-set",
      "npm:core-js@2.1.1/modules/es7.array.includes",
      "npm:core-js@2.1.1/modules/es7.error.is-error",
      "npm:core-js@2.1.1/modules/es7.map.to-json",
      "npm:core-js@2.1.1/modules/es7.math.iaddh",
      "npm:core-js@2.1.1/modules/es7.math.imulh",
      "npm:core-js@2.1.1/modules/es7.math.isubh",
      "npm:core-js@2.1.1/modules/es7.math.umulh",
      "npm:core-js@2.1.1/modules/es7.object.entries",
      "npm:core-js@2.1.1/modules/es7.object.get-own-property-descriptors",
      "npm:core-js@2.1.1/modules/es7.object.values",
      "npm:core-js@2.1.1/modules/es7.reflect.define-metadata",
      "npm:core-js@2.1.1/modules/es7.reflect.delete-metadata",
      "npm:core-js@2.1.1/modules/es7.reflect.get-metadata",
      "npm:core-js@2.1.1/modules/es7.reflect.get-metadata-keys",
      "npm:core-js@2.1.1/modules/es7.reflect.get-own-metadata",
      "npm:core-js@2.1.1/modules/es7.reflect.get-own-metadata-keys",
      "npm:core-js@2.1.1/modules/es7.reflect.has-metadata",
      "npm:core-js@2.1.1/modules/es7.reflect.has-own-metadata",
      "npm:core-js@2.1.1/modules/es7.reflect.metadata",
      "npm:core-js@2.1.1/modules/es7.set.to-json",
      "npm:core-js@2.1.1/modules/es7.string.at",
      "npm:core-js@2.1.1/modules/es7.string.pad-end",
      "npm:core-js@2.1.1/modules/es7.string.pad-start",
      "npm:core-js@2.1.1/modules/es7.string.trim-left",
      "npm:core-js@2.1.1/modules/es7.string.trim-right",
      "npm:core-js@2.1.1/modules/es7.system.global",
      "npm:core-js@2.1.1/modules/web.dom.iterable",
      "npm:core-js@2.1.1/modules/web.immediate",
      "npm:core-js@2.1.1/modules/web.timers",
      "npm:core-js@2.1.1/shim",
      "npm:process@0.11.2",
      "npm:process@0.11.2/browser"
    ]
  },
  depCache: {
    "about": [
      "lib/view/model/abstract"
    ],
    "app": [
      "npm:aurelia-framework@1.0.0-beta.1.1.3"
    ],
    "contact": [
      "npm:aurelia-framework@1.0.0-beta.1.1.3",
      "github:github/fetch@0.10.1",
      "npm:aurelia-fetch-client@1.0.0-beta.1.0.2",
      "lib/app/config",
      "lib/view/model/abstract",
      "github:guillaumepotier/Parsley.js@2.3.4",
      "github:guillaumepotier/Parsley.js@2.3.4/dist/i18n/ro"
    ],
    "diploma": [
      "lib/view/model/abstract"
    ],
    "donate": [
      "github:aurelia/validation@0.6.2",
      "npm:aurelia-framework@1.0.0-beta.1.1.3",
      "github:github/fetch@0.10.1",
      "npm:aurelia-fetch-client@1.0.0-beta.1.0.2",
      "lib/app/config",
      "lib/view/model/abstract",
      "github:seiyria/bootstrap-slider@6.0.17",
      "github:guillaumepotier/Parsley.js@2.3.4",
      "github:guillaumepotier/Parsley.js@2.3.4/dist/i18n/ro",
      "github:braintree/braintree-web@2.21.0",
      "github:tsironis/lockr@0.8.4"
    ],
    "index": [
      "npm:aurelia-framework@1.0.0-beta.1.1.3",
      "npm:aurelia-fetch-client@1.0.0-beta.1.0.2",
      "github:github/fetch@0.10.1",
      "lib/app/config",
      "lib/view/model/abstract"
    ],
    "main": [
      "github:twbs/bootstrap@3.3.6"
    ],
    "support-router": [
      "lib/view/model/abstract"
    ],
    "terms-router": [
      "lib/view/model/abstract"
    ]
  }
})