<?php

/**
 * The array of Forestry Units that already have offered trees
 * @var array
 */

return [
    [
        'id' => 1,
        'unitName' => 'RPLP Kronstadt RA',
        'trees' => '3500',
        'gps' => '',
        'gpuDetails' => '',
        'county' => '',
    ], [
        'id' => 2,
        'unitName' => 'RPLP Piatra Craiului RA',
        'trees' => '10500',
        'gps' => '',
        'gpuDetails' => '',
    ], [
        'id' => 3,
        'unitName' => 'OS Ciucaş RA',
        'trees' => '5075',
        'gps' => '',
        'gpuDetails' => '',
    ], [
        'id' => 4,
        'unitName' => 'RPL OS Râşnov RA',
        'trees' => '10200',
        'gps' => '',
        'gpuDetails' => '',
    ], [
        'id' => 5,
        'unitName' => 'RPLP Stejarul RA',
        'trees' => '15000',
        'gps' => '',
        'gpuDetails' => '',
    ], [
        'id' => 6,
        'unitName' => 'OS Pădurea Bogăţii RA',
        'trees' => '10000',
        'gps' => '',
        'gpuDetails' => '',
    ], [
        'id' => 7,
        'unitName' => 'RPL OS Pădurile Şincii RA',
        'trees' => '5900',
        'gps' => '',
        'gpuDetails' => '',
    ], [
        'id' => 8,
        'unitName' => 'RPLP Săcele RA',
        'trees' => '0',
        'gps' => '45.9824000,24.9486139',
        'gpuDetails' => '',
    ], [
        'id' => 9,
        'unitName' => 'OS Codrii Cetăţilor RA',
        'trees' => '8000',
        'gps' => '',
        'gpuDetails' => '',
    ], [
        'id' => 10,
        'unitName' => 'RPLP Măieruş RA',
        'trees' => '6500',
        'gps' => '',
        'gpuDetails' => '',
    ], [
        'id' => 11,
        'unitName' => 'RPL Bucegi Piatra Craiului RA',
        'trees' => '0',
        'gps' => '',
        'gpuDetails' => '',
    ],  [
        'id' => 12,
        'unitName' => 'OS Padurile Fagarasului',
        'trees' => '5000',
        'gps' => '45.8824000,24.8486139',
        'gpuDetails' => '',
    ], [
        'id' => 13,
        'unitName' => 'OS Braşov',
        'trees' => '4500',
        'gps' => '45.4938889,26.0213889',
        'gpuDetails' => '',
    ], [
        'id' => 14,
        'unitName' => 'OS Teliu',
        'trees' => '0',
        'gps' => '45.5130556,26.0436111',
        'gpuDetails' => '',
    ], [
        'id' => 15,
        'unitName' => 'OS Făgăraş',
        'trees' => '4300',
        'gps' => '',
        'gpuDetails' => '',
    ], [
        'id' => 16,
        'unitName' => 'PL Sacele (ICAS)',
        'trees' => '0',
        'gps' => '',
        'gpuDetails' => '',
    ], [
        'id' => 17,
        'unitName' => 'OS Buzăul Ardelean RA',
        'trees' => '10300',
        'gps' => '',
        'gpuDetails' => '',
    ], [
        'id' => 18,
        'unitName' => 'OSP Baraolt',
        'trees' => '0',
        'gps' => '',
        'gpuDetails' => '',
    ], [
        'id' => 19,
        'unitName' => 'OSP Breţcu',
        'trees' => '10150',
        'gps' => '',
        'gpuDetails' => '',
    ], [
        'id' => 20,
        'unitName' => 'OSP Mereni',
        'trees' => '10000',
        'gps' => '',
        'gpuDetails' => '',
    ], [
        'id' => 21,
        'unitName' => 'OSP Zagon',
        'trees' => '0',
        'gps' => '',
        'gpuDetails' => '',
    ], [
        'id' => 22,
        'unitName' => 'OS Hatod SRL',
        'trees' => '0',
        'gps' => '',
        'gpuDetails' => '',
    ], [
        'id' => 23,
        'unitName' => 'OSP Târgu Secuiesc',
        'trees' => '2500',
        'gps' => '',
        'gpuDetails' => '',
    ], [
        'id' => 24,
        'unitName' => 'OS Breţcu',
        'trees' => '0',
        'gps' => '',
        'gpuDetails' => '',
    ], [
        'id' => 25,
        'unitName' => 'OS Comandău',
        'trees' => '0',
        'gps' => '',
        'gpuDetails' => '',
    ], [
        'id' => 26,
        'unitName' => 'OS Covasna',
        'trees' => '0',
        'gps' => '',
        'gpuDetails' => '',
    ], [
        'id' => 27,
        'unitName' => 'OS Tălişoara',
        'trees' => '0',
        'gps' => '',
        'gpuDetails' => '',
    ], [
        'id' => 28,
        'unitName' => 'OS Frumoasa SRL',
        'trees' => '11150',
        'gps' => '',
        'gpuDetails' => '',
    ], [
        'id' => 29,
        'unitName' => 'OSR Ciuc',
        'trees' => '0',
        'gps' => '',
        'gpuDetails' => '',
    ], [
        'id' => 30,
        'unitName' => 'OSP Liban-Zetea',
        'trees' => '11200',
        'gps' => '',
        'gpuDetails' => '',
    ], [
        'id' => 31,
        'unitName' => 'OSR Gheorgheni SA',
        'trees' => '4500',
        'gps' => '',
        'gpuDetails' => '',
    ], [
        'id' => 32,
        'unitName' => 'OSP Odorheiu Secuiesc',
        'trees' => '2500',
        'gps' => '',
        'gpuDetails' => '',
    ], [
        'id' => 33,
        'unitName' => 'OSP Praid',
        'trees' => '13000',
        'gps' => '',
        'gpuDetails' => '',
    ], [
        'id' => 34,
        'unitName' => 'OSP Gheorgheni',
        'trees' => '11530',
        'gps' => '',
        'gpuDetails' => '',
    ], [
        'id' => 35,
        'unitName' => 'OS Borsec',
        'trees' => '0',
        'gps' => '',
        'gpuDetails' => '',
    ], [
        'id' => 36,
        'unitName' => 'OS Homorod',
        'trees' => '0',
        'gps' => '',
        'gpuDetails' => '',
    ], [
        'id' => 37,
        'unitName' => 'OS Miercurea Ciuc',
        'trees' => '0',
        'gps' => '',
        'gpuDetails' => '',
    ], [
        'id' => 38,
        'unitName' => 'OS Topliţa',
        'trees' => '0',
        'gps' => '',
        'gpuDetails' => '',
    ], [
        'id' => 39,
        'unitName' => 'OS Tulgheş',
        'trees' => '0',
        'gps' => '',
        'gpuDetails' => '',
    ], [
        'id' => 40,
        'unitName' => 'OS Ghindari',
        'trees' => '8000',
        'gps' => '',
        'gpuDetails' => '',
    ], [
        'id' => 41,
        'unitName' => 'OS Vătava',
        'trees' => '4000',
        'gps' => '',
        'gpuDetails' => '',
    ], [
        'id' => 42,
        'unitName' => 'Filiala OS Muresul Sovata',
        'trees' => '0',
        'gps' => '',
        'gpuDetails' => '',
    ], [
        'id' => 43,
        'unitName' => 'OS Fâncel',
        'trees' => '0',
        'gps' => '',
        'gpuDetails' => '',
    ], [
        'id' => 44,
        'unitName' => 'OS Gurghiu',
        'trees' => '0',
        'gps' => '',
        'gpuDetails' => '',
    ], [
        'id' => 45,
        'unitName' => 'OS Luduş',
        'trees' => '0',
        'gps' => '',
        'gpuDetails' => '',
    ], [
        'id' => 46,
        'unitName' => 'OS Lunca Bradului',
        'trees' => '0',
        'gps' => '',
        'gpuDetails' => '',
    ], [
        'id' => 47,
        'unitName' => 'OS Răstoliţa',
        'trees' => '0',
        'gps' => '',
        'gpuDetails' => '',
    ], [
        'id' => 48,
        'unitName' => 'OS Reghin',
        'trees' => '0',
        'gps' => '',
        'gpuDetails' => '',
    ], [
        'id' => 49,
        'unitName' => 'OS Sighişoara',
        'trees' => '0',
        'gps' => '',
        'gpuDetails' => '',
    ], [
        'id' => 50,
        'unitName' => 'OS Tg. Mureş',
        'trees' => '0',
        'gps' => '',
        'gpuDetails' => '',
    ], [
        'id' => 51,
        'unitName' => 'OS Târnăveni',
        'trees' => '0',
        'gps' => '',
        'gpuDetails' => '',
    ], [
        'id' => 52,
        'unitName' => 'OS Sovata',
        'trees' => '19450',
        'gps' => '',
        'gpuDetails' => '',
    ], [
        'id' => 53,
        'unitName' => 'O.S. Răşinari RA',
        'trees' => '0',
        'gps' => '',
        'gpuDetails' => '',
    ], [
        'id' => 54,
        'unitName' => 'S.C. O.S. Jina SRL',
        'trees' => '6000',
        'gps' => '',
        'gpuDetails' => '',
    ], [
        'id' => 55,
        'unitName' => 'RPL O.S. Dealul Sibiului RA',
        'trees' => '10500',
        'gps' => '',
        'gpuDetails' => '',
    ], [
        'id' => 56,
        'unitName' => 'O.S. Izvorul Florii RA',
        'trees' => '0',
        'gps' => '',
        'gpuDetails' => '',
    ], [
        'id' => 57,
        'unitName' => 'RPL. O.S. Cindrel RA',
        'trees' => '10600',
        'gps' => '',
        'gpuDetails' => '',
    ], [
        'id' => 58,
        'unitName' => 'RPL O.S. Tălmaciu RA',
        'trees' => '0',
        'gps' => '',
        'gpuDetails' => '',
    ], [
        'id' => 59,
        'unitName' => 'RPL.O.S. Gura – Râului RA',
        'trees' => '10100',
        'gps' => '',
        'gpuDetails' => '',
    ], [
        'id' => 60,
        'unitName' => 'O.S. Valea Frumoasei RA',
        'trees' => '8000',
        'gps' => '',
        'gpuDetails' => '',
    ], [
        'id' => 61,
        'unitName' => 'RPL O.S. Valea Sadului RA',
        'trees' => '10850',
        'gps' => '',
        'gpuDetails' => '',
    ], [
        'id' => 62,
        'unitName' => 'OS Agnita',
        'trees' => '0',
        'gps' => '',
        'gpuDetails' => '',
    ], [
        'id' => 63,
        'unitName' => 'OS Arpaş',
        'trees' => '0',
        'gps' => '',
        'gpuDetails' => '',
    ], [
        'id' => 64,
        'unitName' => 'OS Avrig',
        'trees' => '0',
        'gps' => '',
        'gpuDetails' => '',
    ], [
        'id' => 65,
        'unitName' => 'OS Dumbrăveni',
        'trees' => '0',
        'gps' => '',
        'gpuDetails' => '',
    ], [
        'id' => 66,
        'unitName' => 'OS Mediaş',
        'trees' => '0',
        'gps' => '',
        'gpuDetails' => '',
    ], [
        'id' => 67,
        'unitName' => 'OS Miercuea Sibiului',
        'trees' => '0',
        'gps' => '',
        'gpuDetails' => '',
    ], [
        'id' => 68,
        'unitName' => 'OS Sibiu',
        'trees' => '0',
        'gps' => '',
        'gpuDetails' => '',
    ], [
        'id' => 69,
        'unitName' => 'OS Vl. Cibinului-Sălişte',
        'trees' => '0',
        'gps' => '',
        'gpuDetails' => '',
    ], [
        'id' => 70,
        'unitName' => 'R.P.L. O.S. Valea Orastiei R.A.',
        'trees' => '3300',
        'gps' => '',
        'gpuDetails' => '',
    ], [
        'id' => 71,
        'unitName' => 'SC Nordix Gheron SRL	',
        'trees' => '10000',
        'gps' => '',
        'gpuDetails' => '',
    ], [
        'id' => 72,
        'unitName' => 'OS Feldru',
        'trees' => '10000',
        'gps' => '',
        'gpuDetails' => '',
    ], [
        'id' => 73,
        'unitName' => 'OS Dealu Negru',
        'trees' => '6000',
        'gps' => '',
        'gpuDetails' => '',
    ], [
        'id' => 74,
        'unitName' => 'O.S.C Romuli R.A',
        'trees' => '6200',
        'gps' => '',
        'gpuDetails' => '',
    ],

];
